-- SUPABASE SCHEMA UPDATED AT: 2026-10-02 (live catalog, read-only)
-- Source: Supabase PostgreSQL catalog; public schema; transaction READ ONLY.
-- Structure only: tables, columns, sequences, constraints, views, and indexes. No row data.
-- Live RPC reference (not re-declared here): transition_laundry_order(p_donhangid bigint, p_trangthaimoi text, p_lydo text DEFAULT NULL) RETURNS void.
-- The RPC derives its actor from auth.uid() and writes NhatKyHeThong; do not bypass its Supabase JWT authorization.

CREATE SEQUENCE "public"."BangGia_BangGiaID_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1 NO CYCLE;
CREATE SEQUENCE "public"."Booking_BookingID_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1 NO CYCLE;
CREATE SEQUENCE "public"."ChiTietDonHang_ChiTietDonHangID_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1 NO CYCLE;
CREATE SEQUENCE "public"."DanhGia_DanhGiaID_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1 NO CYCLE;
CREATE SEQUENCE "public"."DichVu_DichVuID_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1 NO CYCLE;
CREATE SEQUENCE "public"."DiemTichLuy_DiemTichLuyID_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1 NO CYCLE;
CREATE SEQUENCE "public"."DonHang_DonHangID_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1 NO CYCLE;
CREATE SEQUENCE "public"."DonViTinh_DonViTinhID_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1 NO CYCLE;
CREATE SEQUENCE "public"."GiaoNhan_GiaoNhanID_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1 NO CYCLE;
CREATE SEQUENCE "public"."HoaDon_HoaDonID_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1 NO CYCLE;
CREATE SEQUENCE "public"."KhachHang_KhachHangID_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1 NO CYCLE;
CREATE SEQUENCE "public"."KhuyenMai_KhuyenMaiID_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1 NO CYCLE;
CREATE SEQUENCE "public"."LichSuThayDoiHoaDon_LichSuID_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1 NO CYCLE;
CREATE SEQUENCE "public"."LoaiDichVu_LoaiDichVuID_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1 NO CYCLE;
CREATE SEQUENCE "public"."LoaiDoGiat_LoaiDoGiatID_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1 NO CYCLE;
CREATE SEQUENCE "public"."NhanVien_NhanVienID_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1 NO CYCLE;
CREATE SEQUENCE "public"."Quyen_QuyenID_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1 NO CYCLE;
CREATE SEQUENCE "public"."TaiKhoan_TaiKhoanID_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1 NO CYCLE;
CREATE SEQUENCE "public"."ThanhToan_ThanhToanID_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1 NO CYCLE;
CREATE SEQUENCE "public"."ThongBao_ThongBaoID_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1 NO CYCLE;
CREATE SEQUENCE "public"."TinNhan_TinNhanID_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1 NO CYCLE;
CREATE SEQUENCE "public"."VaiTro_VaiTroID_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1 NO CYCLE;
CREATE TABLE "public"."BangGia" (
    "BangGiaID" integer DEFAULT nextval('"BangGia_BangGiaID_seq"'::regclass) NOT NULL,
    "DichVuID" integer NOT NULL,
    "LoaiDoGiatID" integer NOT NULL,
    "DonViTinhID" integer NOT NULL,
    "DonGia" numeric(18,2) NOT NULL,
    "NgayApDung" date NOT NULL,
    "NgayKetThuc" date,
    "TrangThai" character varying(30) DEFAULT 'Hoạt động'::character varying NOT NULL
);

CREATE TABLE "public"."Booking" (
    "BookingID" integer DEFAULT nextval('"Booking_BookingID_seq"'::regclass) NOT NULL,
    "MaBooking" character varying(30) NOT NULL,
    "KhachHangID" integer NOT NULL,
    "HinhThucNhanDo" character varying(30) NOT NULL,
    "DiaChiNhan" character varying(255),
    "NgayHen" date NOT NULL,
    "GioHen" time without time zone NOT NULL,
    "GhiChu" character varying(500),
    "TrangThai" character varying(30) DEFAULT 'ChoTiepNhan'::character varying NOT NULL,
    "NgayTao" timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "NgayCapNhat" timestamp without time zone,
    "IdempotencyKey" uuid,
    "NhanVienID" integer,
    "NhanVienXacNhanID" integer,
    "ThoiGianXacNhan" timestamp without time zone
);

CREATE TABLE "public"."ChiTietBooking" (
    "ChiTietBookingID" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "BookingID" integer NOT NULL,
    "DichVuID" integer NOT NULL,
    "LoaiDoGiatID" integer NOT NULL,
    "DonViTinhID" integer NOT NULL,
    "SoLuong" numeric,
    "KhoiLuong" numeric,
    "DonGia" numeric DEFAULT 0 NOT NULL,
    "ThanhTien" numeric DEFAULT 0 NOT NULL,
    "GhiChu" character varying
);

CREATE TABLE "public"."ChiTietDonHang" (
    "ChiTietDonHangID" integer DEFAULT nextval('"ChiTietDonHang_ChiTietDonHangID_seq"'::regclass) NOT NULL,
    "DonHangID" integer NOT NULL,
    "DichVuID" integer NOT NULL,
    "LoaiDoGiatID" integer NOT NULL,
    "DonViTinhID" integer NOT NULL,
    "SoLuong" numeric(10,2),
    "KhoiLuong" numeric(10,2),
    "DonGia" numeric(18,2) NOT NULL,
    "ThanhTien" numeric(18,2) NOT NULL,
    "GhiChu" character varying(500)
);

CREATE TABLE "public"."DanhGia" (
    "DanhGiaID" integer DEFAULT nextval('"DanhGia_DanhGiaID_seq"'::regclass) NOT NULL,
    "DonHangID" integer NOT NULL,
    "KhachHangID" integer NOT NULL,
    "SoSao" integer NOT NULL,
    "BinhLuan" character varying(1000),
    "NgayDanhGia" timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "TrangThai" character varying(30) DEFAULT 'Hiển thị'::character varying NOT NULL
);

CREATE TABLE "public"."DichVu" (
    "DichVuID" integer DEFAULT nextval('"DichVu_DichVuID_seq"'::regclass) NOT NULL,
    "LoaiDichVuID" integer NOT NULL,
    "TenDichVu" character varying(150) NOT NULL,
    "MoTa" character varying(500),
    "ThoiGianDuKien" integer,
    "TrangThai" character varying(30) DEFAULT 'Hoạt động'::character varying NOT NULL,
    "NgayTao" timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE "public"."DiemTichLuy" (
    "DiemTichLuyID" integer DEFAULT nextval('"DiemTichLuy_DiemTichLuyID_seq"'::regclass) NOT NULL,
    "KhachHangID" integer NOT NULL,
    "DiemHienTai" integer DEFAULT 0 NOT NULL,
    "NgayCapNhat" timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE "public"."DonHang" (
    "DonHangID" integer DEFAULT nextval('"DonHang_DonHangID_seq"'::regclass) NOT NULL,
    "MaDonHang" character varying(30) NOT NULL,
    "BookingID" integer,
    "KhachHangID" integer NOT NULL,
    "NhanVienID" integer,
    "TrangThai" character varying(30) DEFAULT 'Chờ tiếp nhận'::character varying NOT NULL,
    "TongTien" numeric(18,2) DEFAULT 0 NOT NULL,
    "DiemSuDung" integer DEFAULT 0 NOT NULL,
    "TienGiamDoDiem" numeric(18,2) DEFAULT 0 NOT NULL,
    "KhuyenMaiID" integer,
    "TienGiamKhuyenMai" numeric(18,2) DEFAULT 0 NOT NULL,
    "PhiGiaoHang" numeric(18,2) DEFAULT 0 NOT NULL,
    "ThanhTien" numeric(18,2) DEFAULT 0 NOT NULL,
    "GhiChu" character varying(500),
    "NgayTao" timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "NgayCapNhat" timestamp without time zone,
    "IdempotencyKey" uuid
);

CREATE TABLE "public"."DonViTinh" (
    "DonViTinhID" integer DEFAULT nextval('"DonViTinh_DonViTinhID_seq"'::regclass) NOT NULL,
    "TenDonViTinh" character varying(50) NOT NULL,
    "KyHieu" character varying(20),
    "TrangThai" character varying(30) DEFAULT 'Hoạt động'::character varying NOT NULL
);

CREATE TABLE "public"."GiaoNhan" (
    "GiaoNhanID" integer DEFAULT nextval('"GiaoNhan_GiaoNhanID_seq"'::regclass) NOT NULL,
    "DonHangID" integer NOT NULL,
    "NhanVienID" integer,
    "LoaiGiaoNhan" character varying(30) NOT NULL,
    "HinhThuc" character varying(30) NOT NULL,
    "DiaChi" character varying(255),
    "ThoiGianDuKien" timestamp without time zone,
    "ThoiGianThucTe" timestamp without time zone,
    "PhiGiaoNhan" numeric(18,2) DEFAULT 0 NOT NULL,
    "TrangThai" character varying(30) DEFAULT 'Chờ thực hiện'::character varying NOT NULL,
    "GhiChu" character varying(500)
);

CREATE TABLE "public"."HoaDon" (
    "HoaDonID" integer DEFAULT nextval('"HoaDon_HoaDonID_seq"'::regclass) NOT NULL,
    "MaHoaDon" character varying(30) NOT NULL,
    "DonHangID" integer NOT NULL,
    "TongTien" numeric(18,2) NOT NULL,
    "GiamGia" numeric(18,2) DEFAULT 0 NOT NULL,
    "PhiGiaoHang" numeric(18,2) DEFAULT 0 NOT NULL,
    "ThanhTien" numeric(18,2) NOT NULL,
    "NgayLap" timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "TrangThai" character varying(30) DEFAULT 'Chưa thanh toán'::character varying NOT NULL
);

CREATE TABLE "public"."KhachHang" (
    "KhachHangID" integer DEFAULT nextval('"KhachHang_KhachHangID_seq"'::regclass) NOT NULL,
    "HoTen" character varying(100) NOT NULL,
    "SoDienThoai" character varying(15),
    "Email" character varying(150),
    "DiaChi" character varying(255),
    "NgayTao" timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "TrangThai" character varying(30) DEFAULT 'Hoạt động'::character varying NOT NULL
);

CREATE TABLE "public"."KhuyenMai" (
    "KhuyenMaiID" integer DEFAULT nextval('"KhuyenMai_KhuyenMaiID_seq"'::regclass) NOT NULL,
    "MaKhuyenMai" character varying(50) NOT NULL,
    "TenKhuyenMai" character varying(150) NOT NULL,
    "LoaiKhuyenMai" character varying(30) NOT NULL,
    "GiaTriGiam" numeric(18,2) NOT NULL,
    "GiaTriDonToiThieu" numeric(18,2),
    "MucGiamToiDa" numeric(18,2),
    "SoLuongSuDung" integer,
    "DieuKienApDung" character varying(500),
    "NgayBatDau" date NOT NULL,
    "NgayKetThuc" date NOT NULL,
    "TrangThai" character varying(30) DEFAULT 'Hoạt động'::character varying NOT NULL
);

CREATE TABLE "public"."LichSuThayDoiHoaDon" (
    "LichSuID" integer DEFAULT nextval('"LichSuThayDoiHoaDon_LichSuID_seq"'::regclass) NOT NULL,
    "HoaDonID" integer NOT NULL,
    "TaiKhoanID" integer NOT NULL,
    "ThoiGian" timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "TruongThayDoi" character varying(100) NOT NULL,
    "GiaTriCu" character varying(500),
    "GiaTriMoi" character varying(500),
    "LyDo" character varying(500)
);

CREATE TABLE "public"."LoaiDichVu" (
    "LoaiDichVuID" integer DEFAULT nextval('"LoaiDichVu_LoaiDichVuID_seq"'::regclass) NOT NULL,
    "TenLoaiDichVu" character varying(100) NOT NULL,
    "MoTa" character varying(255),
    "TrangThai" character varying(30) DEFAULT 'Hoạt động'::character varying NOT NULL
);

CREATE TABLE "public"."LoaiDoGiat" (
    "LoaiDoGiatID" integer DEFAULT nextval('"LoaiDoGiat_LoaiDoGiatID_seq"'::regclass) NOT NULL,
    "TenLoaiDoGiat" character varying(150) NOT NULL,
    "MoTa" character varying(255),
    "TrangThai" character varying(30) DEFAULT 'Hoạt động'::character varying NOT NULL
);

CREATE TABLE "public"."NhanVien" (
    "NhanVienID" integer DEFAULT nextval('"NhanVien_NhanVienID_seq"'::regclass) NOT NULL,
    "HoTen" character varying(100) NOT NULL,
    "SoDienThoai" character varying(15) NOT NULL,
    "Email" character varying(150),
    "DiaChi" character varying(255),
    "ChucDanh" character varying(100),
    "NgayVaoLam" date,
    "TrangThai" character varying(30) DEFAULT 'Hoạt động'::character varying NOT NULL
);

CREATE TABLE "public"."Quyen" (
    "QuyenID" integer DEFAULT nextval('"Quyen_QuyenID_seq"'::regclass) NOT NULL,
    "MaQuyen" character varying(100) NOT NULL,
    "TenQuyen" character varying(150) NOT NULL,
    "MoTa" character varying(255),
    "TrangThai" character varying(30) DEFAULT 'Hoạt động'::character varying NOT NULL
);

CREATE TABLE "public"."TaiKhoan" (
    "TaiKhoanID" integer DEFAULT nextval('"TaiKhoan_TaiKhoanID_seq"'::regclass) NOT NULL,
    "TenDangNhap" character varying(100) NOT NULL,
    "MatKhau" character varying(255),
    "Email" character varying(150),
    "SoDienThoai" character varying(15),
    "NhanVienID" integer,
    "KhachHangID" integer,
    "TrangThai" character varying(30) DEFAULT 'Hoạt động'::character varying NOT NULL,
    "NgayTao" timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "UserAuthId" uuid
);

CREATE TABLE "public"."TaiKhoan_VaiTro" (
    "TaiKhoanID" integer NOT NULL,
    "VaiTroID" integer NOT NULL
);

CREATE TABLE "public"."ThanhToan" (
    "ThanhToanID" integer DEFAULT nextval('"ThanhToan_ThanhToanID_seq"'::regclass) NOT NULL,
    "DonHangID" integer NOT NULL,
    "SoTien" numeric(18,2) NOT NULL,
    "PhuongThuc" character varying(30) NOT NULL,
    "MaGiaoDich" character varying(100),
    "ThoiGian" timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "TrangThai" character varying(30) DEFAULT 'Chờ thanh toán'::character varying NOT NULL,
    "GhiChu" character varying(500)
);

CREATE TABLE "public"."ThongBao" (
    "ThongBaoID" integer DEFAULT nextval('"ThongBao_ThongBaoID_seq"'::regclass) NOT NULL,
    "TaiKhoanID" integer NOT NULL,
    "DonHangID" integer,
    "LoaiThongBao" character varying(50),
    "TieuDe" character varying(200) NOT NULL,
    "NoiDung" character varying(1000) NOT NULL,
    "ThoiGianGui" timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "DaDoc" boolean DEFAULT false NOT NULL
);

CREATE TABLE "public"."TinNhan" (
    "TinNhanID" integer DEFAULT nextval('"TinNhan_TinNhanID_seq"'::regclass) NOT NULL,
    "NguoiGuiID" integer NOT NULL,
    "NguoiNhanID" integer NOT NULL,
    "DonHangID" integer,
    "NoiDung" character varying(1000) NOT NULL,
    "ThoiGianGui" timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "TrangThai" character varying(30) DEFAULT 'Đã gửi'::character varying NOT NULL
);

CREATE TABLE "public"."VaiTro" (
    "VaiTroID" integer DEFAULT nextval('"VaiTro_VaiTroID_seq"'::regclass) NOT NULL,
    "TenVaiTro" character varying(100) NOT NULL,
    "MoTa" character varying(255),
    "TrangThai" character varying(30) DEFAULT 'Hoạt động'::character varying NOT NULL
);

CREATE TABLE "public"."VaiTro_Quyen" (
    "VaiTroID" integer NOT NULL,
    "QuyenID" integer NOT NULL
);

CREATE TABLE "public"."NhatKyHeThong" (
    "NhatKyID" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "TaiKhoanID" integer,
    "HanhDong" character varying NOT NULL,
    "BangDuLieu" character varying NOT NULL,
    "BanGhiID" bigint,
    "DuLieuCu" jsonb,
    "DuLieuMoi" jsonb,
    "LyDo" character varying,
    "ThoiGian" timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "IPAddress" character varying,
    "UserAgent" character varying
);

CREATE TABLE "public"."khachhang_diachi" (
    "diachiid" bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
    "khachhangid" bigint NOT NULL,
    "tennguoinhan" character varying(100) NOT NULL,
    "sodienthoai" character varying(15) NOT NULL,
    "diachi" character varying(500) NOT NULL,
    "ghichu" character varying(500),
    "macdinh" boolean DEFAULT false NOT NULL,
    "ngaytao" timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE "public"."sessions" (
    "id" character varying(255) NOT NULL,
    "user_id" bigint,
    "ip_address" character varying(45),
    "user_agent" text,
    "payload" text NOT NULL,
    "last_activity" integer NOT NULL
);

ALTER TABLE ONLY "public"."BangGia" ADD CONSTRAINT "BangGia_DichVuID_fkey" FOREIGN KEY ("DichVuID") REFERENCES "DichVu"("DichVuID");
ALTER TABLE ONLY "public"."BangGia" ADD CONSTRAINT "BangGia_DonGia_check" CHECK ("DonGia" >= 0::numeric);
ALTER TABLE ONLY "public"."BangGia" ADD CONSTRAINT "BangGia_DonViTinhID_fkey" FOREIGN KEY ("DonViTinhID") REFERENCES "DonViTinh"("DonViTinhID");
ALTER TABLE ONLY "public"."BangGia" ADD CONSTRAINT "BangGia_LoaiDoGiatID_fkey" FOREIGN KEY ("LoaiDoGiatID") REFERENCES "LoaiDoGiat"("LoaiDoGiatID");
ALTER TABLE ONLY "public"."BangGia" ADD CONSTRAINT "BangGia_TrangThai_check" CHECK ("TrangThai"::text = ANY (ARRAY['Hoạt động'::character varying, 'Hết hiệu lực'::character varying, 'Tạm ngưng'::character varying]::text[]));
ALTER TABLE ONLY "public"."BangGia" ADD CONSTRAINT "BangGia_pkey" PRIMARY KEY ("BangGiaID");
ALTER TABLE ONLY "public"."BangGia" ADD CONSTRAINT "CK_BangGia_Ngay" CHECK ("NgayKetThuc" IS NULL OR "NgayKetThuc" >= "NgayApDung");
ALTER TABLE ONLY "public"."Booking" ADD CONSTRAINT "Booking_HinhThucNhanDo_check" CHECK ("HinhThucNhanDo"::text = ANY (ARRAY['Tại cửa hàng'::character varying, 'Tại nhà'::character varying]::text[]));
ALTER TABLE ONLY "public"."Booking" ADD CONSTRAINT "Booking_KhachHangID_fkey" FOREIGN KEY ("KhachHangID") REFERENCES "KhachHang"("KhachHangID");
ALTER TABLE ONLY "public"."Booking" ADD CONSTRAINT "Booking_MaBooking_key" UNIQUE ("MaBooking");
ALTER TABLE ONLY "public"."Booking" ADD CONSTRAINT "Booking_NhanVienID_fkey" FOREIGN KEY ("NhanVienID") REFERENCES "NhanVien"("NhanVienID") ON DELETE SET NULL;
ALTER TABLE ONLY "public"."Booking" ADD CONSTRAINT "Booking_NhanVienXacNhanID_fkey" FOREIGN KEY ("NhanVienXacNhanID") REFERENCES "NhanVien"("NhanVienID");
ALTER TABLE ONLY "public"."Booking" ADD CONSTRAINT "Booking_pkey" PRIMARY KEY ("BookingID");
ALTER TABLE ONLY "public"."Booking" ADD CONSTRAINT "booking_trangthai_check" CHECK ("TrangThai"::text = ANY (ARRAY['ChoTiepNhan'::character varying, 'DaXacNhan'::character varying, 'DaHuy'::character varying, 'HoanThanh'::character varying]::text[]));
ALTER TABLE ONLY "public"."ChiTietBooking" ADD CONSTRAINT "ChiTietBooking_BookingID_fkey" FOREIGN KEY ("BookingID") REFERENCES "Booking"("BookingID") ON DELETE CASCADE;
ALTER TABLE ONLY "public"."ChiTietBooking" ADD CONSTRAINT "ChiTietBooking_DichVuID_fkey" FOREIGN KEY ("DichVuID") REFERENCES "DichVu"("DichVuID");
ALTER TABLE ONLY "public"."ChiTietBooking" ADD CONSTRAINT "ChiTietBooking_DonGia_check" CHECK ("DonGia" >= 0::numeric);
ALTER TABLE ONLY "public"."ChiTietBooking" ADD CONSTRAINT "ChiTietBooking_DonViTinhID_fkey" FOREIGN KEY ("DonViTinhID") REFERENCES "DonViTinh"("DonViTinhID");
ALTER TABLE ONLY "public"."ChiTietBooking" ADD CONSTRAINT "ChiTietBooking_KhoiLuong_check" CHECK ("KhoiLuong" IS NULL OR "KhoiLuong" > 0::numeric);
ALTER TABLE ONLY "public"."ChiTietBooking" ADD CONSTRAINT "ChiTietBooking_LoaiDoGiatID_fkey" FOREIGN KEY ("LoaiDoGiatID") REFERENCES "LoaiDoGiat"("LoaiDoGiatID");
ALTER TABLE ONLY "public"."ChiTietBooking" ADD CONSTRAINT "ChiTietBooking_SoLuong_check" CHECK ("SoLuong" IS NULL OR "SoLuong" > 0::numeric);
ALTER TABLE ONLY "public"."ChiTietBooking" ADD CONSTRAINT "ChiTietBooking_ThanhTien_check" CHECK ("ThanhTien" >= 0::numeric);
ALTER TABLE ONLY "public"."ChiTietBooking" ADD CONSTRAINT "ChiTietBooking_measurement_check" CHECK (("SoLuong" IS NOT NULL AND "KhoiLuong" IS NULL) OR ("SoLuong" IS NULL AND "KhoiLuong" IS NOT NULL));
ALTER TABLE ONLY "public"."ChiTietBooking" ADD CONSTRAINT "ChiTietBooking_pkey" PRIMARY KEY ("ChiTietBookingID");
ALTER TABLE ONLY "public"."ChiTietDonHang" ADD CONSTRAINT "CK_CTDH_SoLuongKhoiLuong" CHECK ("SoLuong" IS NOT NULL AND "SoLuong" > 0::numeric OR "KhoiLuong" IS NOT NULL AND "KhoiLuong" > 0::numeric);
ALTER TABLE ONLY "public"."ChiTietDonHang" ADD CONSTRAINT "ChiTietDonHang_DichVuID_fkey" FOREIGN KEY ("DichVuID") REFERENCES "DichVu"("DichVuID");
ALTER TABLE ONLY "public"."ChiTietDonHang" ADD CONSTRAINT "ChiTietDonHang_DonGia_check" CHECK ("DonGia" >= 0::numeric);
ALTER TABLE ONLY "public"."ChiTietDonHang" ADD CONSTRAINT "ChiTietDonHang_DonHangID_fkey" FOREIGN KEY ("DonHangID") REFERENCES "DonHang"("DonHangID");
ALTER TABLE ONLY "public"."ChiTietDonHang" ADD CONSTRAINT "ChiTietDonHang_DonViTinhID_fkey" FOREIGN KEY ("DonViTinhID") REFERENCES "DonViTinh"("DonViTinhID");
ALTER TABLE ONLY "public"."ChiTietDonHang" ADD CONSTRAINT "ChiTietDonHang_LoaiDoGiatID_fkey" FOREIGN KEY ("LoaiDoGiatID") REFERENCES "LoaiDoGiat"("LoaiDoGiatID");
ALTER TABLE ONLY "public"."ChiTietDonHang" ADD CONSTRAINT "ChiTietDonHang_ThanhTien_check" CHECK ("ThanhTien" >= 0::numeric);
ALTER TABLE ONLY "public"."ChiTietDonHang" ADD CONSTRAINT "ChiTietDonHang_pkey" PRIMARY KEY ("ChiTietDonHangID");
ALTER TABLE ONLY "public"."DanhGia" ADD CONSTRAINT "DanhGia_DonHangID_fkey" FOREIGN KEY ("DonHangID") REFERENCES "DonHang"("DonHangID");
ALTER TABLE ONLY "public"."DanhGia" ADD CONSTRAINT "DanhGia_DonHangID_key" UNIQUE ("DonHangID");
ALTER TABLE ONLY "public"."DanhGia" ADD CONSTRAINT "DanhGia_KhachHangID_fkey" FOREIGN KEY ("KhachHangID") REFERENCES "KhachHang"("KhachHangID");
ALTER TABLE ONLY "public"."DanhGia" ADD CONSTRAINT "DanhGia_SoSao_check" CHECK ("SoSao" >= 1 AND "SoSao" <= 5);
ALTER TABLE ONLY "public"."DanhGia" ADD CONSTRAINT "DanhGia_TrangThai_check" CHECK ("TrangThai"::text = ANY (ARRAY['Hiển thị'::character varying, 'Ẩn'::character varying]::text[]));
ALTER TABLE ONLY "public"."DanhGia" ADD CONSTRAINT "DanhGia_pkey" PRIMARY KEY ("DanhGiaID");
ALTER TABLE ONLY "public"."DichVu" ADD CONSTRAINT "DichVu_LoaiDichVuID_fkey" FOREIGN KEY ("LoaiDichVuID") REFERENCES "LoaiDichVu"("LoaiDichVuID");
ALTER TABLE ONLY "public"."DichVu" ADD CONSTRAINT "DichVu_TrangThai_check" CHECK ("TrangThai"::text = ANY (ARRAY['Hoạt động'::character varying, 'Tạm ngưng'::character varying]::text[]));
ALTER TABLE ONLY "public"."DichVu" ADD CONSTRAINT "DichVu_pkey" PRIMARY KEY ("DichVuID");
ALTER TABLE ONLY "public"."DiemTichLuy" ADD CONSTRAINT "DiemTichLuy_DiemHienTai_check" CHECK ("DiemHienTai" >= 0);
ALTER TABLE ONLY "public"."DiemTichLuy" ADD CONSTRAINT "DiemTichLuy_KhachHangID_fkey" FOREIGN KEY ("KhachHangID") REFERENCES "KhachHang"("KhachHangID");
ALTER TABLE ONLY "public"."DiemTichLuy" ADD CONSTRAINT "DiemTichLuy_KhachHangID_key" UNIQUE ("KhachHangID");
ALTER TABLE ONLY "public"."DiemTichLuy" ADD CONSTRAINT "DiemTichLuy_pkey" PRIMARY KEY ("DiemTichLuyID");
ALTER TABLE ONLY "public"."DonHang" ADD CONSTRAINT "DonHang_BookingID_fkey" FOREIGN KEY ("BookingID") REFERENCES "Booking"("BookingID");
ALTER TABLE ONLY "public"."DonHang" ADD CONSTRAINT "DonHang_DiemSuDung_check" CHECK ("DiemSuDung" >= 0);
ALTER TABLE ONLY "public"."DonHang" ADD CONSTRAINT "DonHang_KhachHangID_fkey" FOREIGN KEY ("KhachHangID") REFERENCES "KhachHang"("KhachHangID");
ALTER TABLE ONLY "public"."DonHang" ADD CONSTRAINT "DonHang_KhuyenMaiID_fkey" FOREIGN KEY ("KhuyenMaiID") REFERENCES "KhuyenMai"("KhuyenMaiID");
ALTER TABLE ONLY "public"."DonHang" ADD CONSTRAINT "DonHang_MaDonHang_key" UNIQUE ("MaDonHang");
ALTER TABLE ONLY "public"."DonHang" ADD CONSTRAINT "DonHang_NhanVienID_fkey" FOREIGN KEY ("NhanVienID") REFERENCES "NhanVien"("NhanVienID");
ALTER TABLE ONLY "public"."DonHang" ADD CONSTRAINT "DonHang_PhiGiaoHang_check" CHECK ("PhiGiaoHang" >= 0::numeric);
ALTER TABLE ONLY "public"."DonHang" ADD CONSTRAINT "DonHang_ThanhTien_check" CHECK ("ThanhTien" >= 0::numeric);
ALTER TABLE ONLY "public"."DonHang" ADD CONSTRAINT "DonHang_TienGiamDoDiem_check" CHECK ("TienGiamDoDiem" >= 0::numeric);
ALTER TABLE ONLY "public"."DonHang" ADD CONSTRAINT "DonHang_TienGiamKhuyenMai_check" CHECK ("TienGiamKhuyenMai" >= 0::numeric);
ALTER TABLE ONLY "public"."DonHang" ADD CONSTRAINT "DonHang_TongTien_check" CHECK ("TongTien" >= 0::numeric);
ALTER TABLE ONLY "public"."DonHang" ADD CONSTRAINT "DonHang_TrangThai_check" CHECK ("TrangThai"::text = ANY (ARRAY['Chờ tiếp nhận'::character varying, 'Đã tiếp nhận'::character varying, 'Đang giặt'::character varying, 'Hoàn thành giặt'::character varying, 'Đang giao'::character varying, 'Đã giao'::character varying, 'Đã thanh toán'::character varying, 'Đã hủy'::character varying]::text[]));
ALTER TABLE ONLY "public"."DonHang" ADD CONSTRAINT "DonHang_pkey" PRIMARY KEY ("DonHangID");
ALTER TABLE ONLY "public"."DonViTinh" ADD CONSTRAINT "DonViTinh_TenDonViTinh_key" UNIQUE ("TenDonViTinh");
ALTER TABLE ONLY "public"."DonViTinh" ADD CONSTRAINT "DonViTinh_TrangThai_check" CHECK ("TrangThai"::text = ANY (ARRAY['Hoạt động'::character varying, 'Tạm ngưng'::character varying]::text[]));
ALTER TABLE ONLY "public"."DonViTinh" ADD CONSTRAINT "DonViTinh_pkey" PRIMARY KEY ("DonViTinhID");
ALTER TABLE ONLY "public"."GiaoNhan" ADD CONSTRAINT "GiaoNhan_DonHangID_fkey" FOREIGN KEY ("DonHangID") REFERENCES "DonHang"("DonHangID");
ALTER TABLE ONLY "public"."GiaoNhan" ADD CONSTRAINT "GiaoNhan_HinhThuc_check" CHECK ("HinhThuc"::text = ANY (ARRAY['Tại cửa hàng'::character varying, 'Tại nhà'::character varying]::text[]));
ALTER TABLE ONLY "public"."GiaoNhan" ADD CONSTRAINT "GiaoNhan_LoaiGiaoNhan_check" CHECK ("LoaiGiaoNhan"::text = ANY (ARRAY['NHAN_DO'::character varying, 'GIAO_DO'::character varying]::text[]));
ALTER TABLE ONLY "public"."GiaoNhan" ADD CONSTRAINT "GiaoNhan_NhanVienID_fkey" FOREIGN KEY ("NhanVienID") REFERENCES "NhanVien"("NhanVienID");
ALTER TABLE ONLY "public"."GiaoNhan" ADD CONSTRAINT "GiaoNhan_PhiGiaoNhan_check" CHECK ("PhiGiaoNhan" >= 0::numeric);
ALTER TABLE ONLY "public"."GiaoNhan" ADD CONSTRAINT "GiaoNhan_TrangThai_check" CHECK ("TrangThai"::text = ANY (ARRAY['Chờ thực hiện'::character varying, 'Đang thực hiện'::character varying, 'Hoàn thành'::character varying, 'Đã hủy'::character varying]::text[]));
ALTER TABLE ONLY "public"."GiaoNhan" ADD CONSTRAINT "GiaoNhan_pkey" PRIMARY KEY ("GiaoNhanID");
ALTER TABLE ONLY "public"."HoaDon" ADD CONSTRAINT "HoaDon_DonHangID_fkey" FOREIGN KEY ("DonHangID") REFERENCES "DonHang"("DonHangID");
ALTER TABLE ONLY "public"."HoaDon" ADD CONSTRAINT "HoaDon_DonHangID_key" UNIQUE ("DonHangID");
ALTER TABLE ONLY "public"."HoaDon" ADD CONSTRAINT "HoaDon_GiamGia_check" CHECK ("GiamGia" >= 0::numeric);
ALTER TABLE ONLY "public"."HoaDon" ADD CONSTRAINT "HoaDon_MaHoaDon_key" UNIQUE ("MaHoaDon");
ALTER TABLE ONLY "public"."HoaDon" ADD CONSTRAINT "HoaDon_PhiGiaoHang_check" CHECK ("PhiGiaoHang" >= 0::numeric);
ALTER TABLE ONLY "public"."HoaDon" ADD CONSTRAINT "HoaDon_ThanhTien_check" CHECK ("ThanhTien" >= 0::numeric);
ALTER TABLE ONLY "public"."HoaDon" ADD CONSTRAINT "HoaDon_TongTien_check" CHECK ("TongTien" >= 0::numeric);
ALTER TABLE ONLY "public"."HoaDon" ADD CONSTRAINT "HoaDon_TrangThai_check" CHECK ("TrangThai"::text = ANY (ARRAY['Chưa thanh toán'::character varying, 'Đã thanh toán'::character varying, 'Đã hủy'::character varying]::text[]));
ALTER TABLE ONLY "public"."HoaDon" ADD CONSTRAINT "HoaDon_pkey" PRIMARY KEY ("HoaDonID");
ALTER TABLE ONLY "public"."KhachHang" ADD CONSTRAINT "KhachHang_SoDienThoai_key" UNIQUE ("SoDienThoai");
ALTER TABLE ONLY "public"."KhachHang" ADD CONSTRAINT "KhachHang_TrangThai_check" CHECK ("TrangThai"::text = ANY (ARRAY['Hoạt động'::character varying, 'Khóa'::character varying, 'Ngừng hoạt động'::character varying]::text[]));
ALTER TABLE ONLY "public"."KhachHang" ADD CONSTRAINT "KhachHang_pkey" PRIMARY KEY ("KhachHangID");
ALTER TABLE ONLY "public"."KhuyenMai" ADD CONSTRAINT "CK_KhuyenMai_Ngay" CHECK ("NgayKetThuc" >= "NgayBatDau");
ALTER TABLE ONLY "public"."KhuyenMai" ADD CONSTRAINT "KhuyenMai_GiaTriGiam_check" CHECK ("GiaTriGiam" >= 0::numeric);
ALTER TABLE ONLY "public"."KhuyenMai" ADD CONSTRAINT "KhuyenMai_LoaiKhuyenMai_check" CHECK ("LoaiKhuyenMai"::text = ANY (ARRAY['Phần trăm'::character varying, 'Tiền mặt'::character varying]::text[]));
ALTER TABLE ONLY "public"."KhuyenMai" ADD CONSTRAINT "KhuyenMai_MaKhuyenMai_key" UNIQUE ("MaKhuyenMai");
ALTER TABLE ONLY "public"."KhuyenMai" ADD CONSTRAINT "KhuyenMai_TrangThai_check" CHECK ("TrangThai"::text = ANY (ARRAY['Hoạt động'::character varying, 'Tạm ngưng'::character varying, 'Hết hạn'::character varying]::text[]));
ALTER TABLE ONLY "public"."KhuyenMai" ADD CONSTRAINT "KhuyenMai_pkey" PRIMARY KEY ("KhuyenMaiID");
ALTER TABLE ONLY "public"."LichSuThayDoiHoaDon" ADD CONSTRAINT "LichSuThayDoiHoaDon_HoaDonID_fkey" FOREIGN KEY ("HoaDonID") REFERENCES "HoaDon"("HoaDonID");
ALTER TABLE ONLY "public"."LichSuThayDoiHoaDon" ADD CONSTRAINT "LichSuThayDoiHoaDon_TaiKhoanID_fkey" FOREIGN KEY ("TaiKhoanID") REFERENCES "TaiKhoan"("TaiKhoanID");
ALTER TABLE ONLY "public"."LichSuThayDoiHoaDon" ADD CONSTRAINT "LichSuThayDoiHoaDon_pkey" PRIMARY KEY ("LichSuID");
ALTER TABLE ONLY "public"."LoaiDichVu" ADD CONSTRAINT "LoaiDichVu_TenLoaiDichVu_key" UNIQUE ("TenLoaiDichVu");
ALTER TABLE ONLY "public"."LoaiDichVu" ADD CONSTRAINT "LoaiDichVu_TrangThai_check" CHECK ("TrangThai"::text = ANY (ARRAY['Hoạt động'::character varying, 'Tạm ngưng'::character varying]::text[]));
ALTER TABLE ONLY "public"."LoaiDichVu" ADD CONSTRAINT "LoaiDichVu_pkey" PRIMARY KEY ("LoaiDichVuID");
ALTER TABLE ONLY "public"."LoaiDoGiat" ADD CONSTRAINT "LoaiDoGiat_TenLoaiDoGiat_key" UNIQUE ("TenLoaiDoGiat");
ALTER TABLE ONLY "public"."LoaiDoGiat" ADD CONSTRAINT "LoaiDoGiat_TrangThai_check" CHECK ("TrangThai"::text = ANY (ARRAY['Hoạt động'::character varying, 'Tạm ngưng'::character varying]::text[]));
ALTER TABLE ONLY "public"."LoaiDoGiat" ADD CONSTRAINT "LoaiDoGiat_pkey" PRIMARY KEY ("LoaiDoGiatID");
ALTER TABLE ONLY "public"."NhanVien" ADD CONSTRAINT "NhanVien_SoDienThoai_key" UNIQUE ("SoDienThoai");
ALTER TABLE ONLY "public"."NhanVien" ADD CONSTRAINT "NhanVien_TrangThai_check" CHECK ("TrangThai"::text = ANY (ARRAY['Hoạt động'::character varying, 'Khóa'::character varying, 'Ngừng hoạt động'::character varying]::text[]));
ALTER TABLE ONLY "public"."NhanVien" ADD CONSTRAINT "NhanVien_pkey" PRIMARY KEY ("NhanVienID");
ALTER TABLE ONLY "public"."Quyen" ADD CONSTRAINT "Quyen_MaQuyen_key" UNIQUE ("MaQuyen");
ALTER TABLE ONLY "public"."Quyen" ADD CONSTRAINT "Quyen_TrangThai_check" CHECK ("TrangThai"::text = ANY (ARRAY['Hoạt động'::character varying, 'Ngừng hoạt động'::character varying]::text[]));
ALTER TABLE ONLY "public"."Quyen" ADD CONSTRAINT "Quyen_pkey" PRIMARY KEY ("QuyenID");
ALTER TABLE ONLY "public"."TaiKhoan" ADD CONSTRAINT "CK_TaiKhoan_DoiTuong" CHECK ("NhanVienID" IS NOT NULL AND "KhachHangID" IS NULL OR "NhanVienID" IS NULL AND "KhachHangID" IS NOT NULL);
ALTER TABLE ONLY "public"."TaiKhoan" ADD CONSTRAINT "TaiKhoan_KhachHangID_fkey" FOREIGN KEY ("KhachHangID") REFERENCES "KhachHang"("KhachHangID");
ALTER TABLE ONLY "public"."TaiKhoan" ADD CONSTRAINT "TaiKhoan_NhanVienID_fkey" FOREIGN KEY ("NhanVienID") REFERENCES "NhanVien"("NhanVienID");
ALTER TABLE ONLY "public"."TaiKhoan" ADD CONSTRAINT "TaiKhoan_Email_key" UNIQUE ("Email");
ALTER TABLE ONLY "public"."TaiKhoan" ADD CONSTRAINT "TaiKhoan_TenDangNhap_key" UNIQUE ("TenDangNhap");
ALTER TABLE ONLY "public"."TaiKhoan" ADD CONSTRAINT "TaiKhoan_TrangThai_check" CHECK ("TrangThai"::text = ANY (ARRAY['Hoạt động'::character varying, 'Khóa'::character varying, 'Ngừng hoạt động'::character varying]::text[]));
ALTER TABLE ONLY "public"."TaiKhoan" ADD CONSTRAINT "TaiKhoan_pkey" PRIMARY KEY ("TaiKhoanID");
ALTER TABLE ONLY "public"."TaiKhoan_VaiTro" ADD CONSTRAINT "TaiKhoan_VaiTro_TaiKhoanID_fkey" FOREIGN KEY ("TaiKhoanID") REFERENCES "TaiKhoan"("TaiKhoanID");
ALTER TABLE ONLY "public"."TaiKhoan_VaiTro" ADD CONSTRAINT "TaiKhoan_VaiTro_VaiTroID_fkey" FOREIGN KEY ("VaiTroID") REFERENCES "VaiTro"("VaiTroID");
ALTER TABLE ONLY "public"."TaiKhoan_VaiTro" ADD CONSTRAINT "TaiKhoan_VaiTro_pkey" PRIMARY KEY ("TaiKhoanID", "VaiTroID");
ALTER TABLE ONLY "public"."ThanhToan" ADD CONSTRAINT "ThanhToan_DonHangID_fkey" FOREIGN KEY ("DonHangID") REFERENCES "DonHang"("DonHangID");
ALTER TABLE ONLY "public"."ThanhToan" ADD CONSTRAINT "ThanhToan_PhuongThuc_check" CHECK ("PhuongThuc"::text = ANY (ARRAY['Tiền mặt'::character varying, 'Chuyển khoản'::character varying]::text[]));
ALTER TABLE ONLY "public"."ThanhToan" ADD CONSTRAINT "ThanhToan_SoTien_check" CHECK ("SoTien" > 0::numeric);
ALTER TABLE ONLY "public"."ThanhToan" ADD CONSTRAINT "ThanhToan_TrangThai_check" CHECK ("TrangThai"::text = ANY (ARRAY['Chờ thanh toán'::character varying, 'Thành công'::character varying, 'Thất bại'::character varying, 'Đã hoàn tiền'::character varying]::text[]));
ALTER TABLE ONLY "public"."ThanhToan" ADD CONSTRAINT "ThanhToan_pkey" PRIMARY KEY ("ThanhToanID");
ALTER TABLE ONLY "public"."ThongBao" ADD CONSTRAINT "ThongBao_DonHangID_fkey" FOREIGN KEY ("DonHangID") REFERENCES "DonHang"("DonHangID");
ALTER TABLE ONLY "public"."ThongBao" ADD CONSTRAINT "ThongBao_TaiKhoanID_fkey" FOREIGN KEY ("TaiKhoanID") REFERENCES "TaiKhoan"("TaiKhoanID");
ALTER TABLE ONLY "public"."ThongBao" ADD CONSTRAINT "ThongBao_pkey" PRIMARY KEY ("ThongBaoID");
ALTER TABLE ONLY "public"."TinNhan" ADD CONSTRAINT "TinNhan_DonHangID_fkey" FOREIGN KEY ("DonHangID") REFERENCES "DonHang"("DonHangID");
ALTER TABLE ONLY "public"."TinNhan" ADD CONSTRAINT "TinNhan_NguoiGuiID_fkey" FOREIGN KEY ("NguoiGuiID") REFERENCES "TaiKhoan"("TaiKhoanID");
ALTER TABLE ONLY "public"."TinNhan" ADD CONSTRAINT "TinNhan_NguoiNhanID_fkey" FOREIGN KEY ("NguoiNhanID") REFERENCES "TaiKhoan"("TaiKhoanID");
ALTER TABLE ONLY "public"."TinNhan" ADD CONSTRAINT "TinNhan_TrangThai_check" CHECK ("TrangThai"::text = ANY (ARRAY['Đã gửi'::character varying, 'Đã nhận'::character varying, 'Đã đọc'::character varying]::text[]));
ALTER TABLE ONLY "public"."TinNhan" ADD CONSTRAINT "TinNhan_pkey" PRIMARY KEY ("TinNhanID");
ALTER TABLE ONLY "public"."VaiTro" ADD CONSTRAINT "VaiTro_TenVaiTro_key" UNIQUE ("TenVaiTro");
ALTER TABLE ONLY "public"."VaiTro" ADD CONSTRAINT "VaiTro_TrangThai_check" CHECK ("TrangThai"::text = ANY (ARRAY['Hoạt động'::character varying, 'Ngừng hoạt động'::character varying]::text[]));
ALTER TABLE ONLY "public"."VaiTro" ADD CONSTRAINT "VaiTro_pkey" PRIMARY KEY ("VaiTroID");
ALTER TABLE ONLY "public"."VaiTro_Quyen" ADD CONSTRAINT "VaiTro_Quyen_QuyenID_fkey" FOREIGN KEY ("QuyenID") REFERENCES "Quyen"("QuyenID");
ALTER TABLE ONLY "public"."VaiTro_Quyen" ADD CONSTRAINT "VaiTro_Quyen_VaiTroID_fkey" FOREIGN KEY ("VaiTroID") REFERENCES "VaiTro"("VaiTroID");
ALTER TABLE ONLY "public"."VaiTro_Quyen" ADD CONSTRAINT "VaiTro_Quyen_pkey" PRIMARY KEY ("VaiTroID", "QuyenID");
ALTER TABLE ONLY "public"."NhatKyHeThong" ADD CONSTRAINT "NhatKyHeThong_TaiKhoanID_fkey" FOREIGN KEY ("TaiKhoanID") REFERENCES "TaiKhoan"("TaiKhoanID");
ALTER TABLE ONLY "public"."NhatKyHeThong" ADD CONSTRAINT "NhatKyHeThong_pkey" PRIMARY KEY ("NhatKyID");
ALTER TABLE ONLY "public"."khachhang_diachi" ADD CONSTRAINT "khachhang_diachi_diachi_check" CHECK (length(btrim(diachi::text)) > 0);
ALTER TABLE ONLY "public"."khachhang_diachi" ADD CONSTRAINT "khachhang_diachi_khachhangid_fkey" FOREIGN KEY (khachhangid) REFERENCES "KhachHang"("KhachHangID") ON DELETE CASCADE;
ALTER TABLE ONLY "public"."khachhang_diachi" ADD CONSTRAINT "khachhang_diachi_pkey" PRIMARY KEY (diachiid);
ALTER TABLE ONLY "public"."khachhang_diachi" ADD CONSTRAINT "khachhang_diachi_sodienthoai_check" CHECK (length(btrim(sodienthoai::text)) >= 8);
ALTER TABLE ONLY "public"."sessions" ADD CONSTRAINT "sessions_pkey" PRIMARY KEY (id);

ALTER SEQUENCE "public"."BangGia_BangGiaID_seq" OWNED BY "public"."BangGia"."BangGiaID";
ALTER SEQUENCE "public"."Booking_BookingID_seq" OWNED BY "public"."Booking"."BookingID";
ALTER SEQUENCE "public"."ChiTietDonHang_ChiTietDonHangID_seq" OWNED BY "public"."ChiTietDonHang"."ChiTietDonHangID";
ALTER SEQUENCE "public"."DanhGia_DanhGiaID_seq" OWNED BY "public"."DanhGia"."DanhGiaID";
ALTER SEQUENCE "public"."DichVu_DichVuID_seq" OWNED BY "public"."DichVu"."DichVuID";
ALTER SEQUENCE "public"."DiemTichLuy_DiemTichLuyID_seq" OWNED BY "public"."DiemTichLuy"."DiemTichLuyID";
ALTER SEQUENCE "public"."DonHang_DonHangID_seq" OWNED BY "public"."DonHang"."DonHangID";
ALTER SEQUENCE "public"."DonViTinh_DonViTinhID_seq" OWNED BY "public"."DonViTinh"."DonViTinhID";
ALTER SEQUENCE "public"."GiaoNhan_GiaoNhanID_seq" OWNED BY "public"."GiaoNhan"."GiaoNhanID";
ALTER SEQUENCE "public"."HoaDon_HoaDonID_seq" OWNED BY "public"."HoaDon"."HoaDonID";
ALTER SEQUENCE "public"."KhachHang_KhachHangID_seq" OWNED BY "public"."KhachHang"."KhachHangID";
ALTER SEQUENCE "public"."KhuyenMai_KhuyenMaiID_seq" OWNED BY "public"."KhuyenMai"."KhuyenMaiID";
ALTER SEQUENCE "public"."LichSuThayDoiHoaDon_LichSuID_seq" OWNED BY "public"."LichSuThayDoiHoaDon"."LichSuID";
ALTER SEQUENCE "public"."LoaiDichVu_LoaiDichVuID_seq" OWNED BY "public"."LoaiDichVu"."LoaiDichVuID";
ALTER SEQUENCE "public"."LoaiDoGiat_LoaiDoGiatID_seq" OWNED BY "public"."LoaiDoGiat"."LoaiDoGiatID";
ALTER SEQUENCE "public"."NhanVien_NhanVienID_seq" OWNED BY "public"."NhanVien"."NhanVienID";
ALTER SEQUENCE "public"."Quyen_QuyenID_seq" OWNED BY "public"."Quyen"."QuyenID";
ALTER SEQUENCE "public"."TaiKhoan_TaiKhoanID_seq" OWNED BY "public"."TaiKhoan"."TaiKhoanID";
ALTER SEQUENCE "public"."ThanhToan_ThanhToanID_seq" OWNED BY "public"."ThanhToan"."ThanhToanID";
ALTER SEQUENCE "public"."ThongBao_ThongBaoID_seq" OWNED BY "public"."ThongBao"."ThongBaoID";
ALTER SEQUENCE "public"."TinNhan_TinNhanID_seq" OWNED BY "public"."TinNhan"."TinNhanID";
ALTER SEQUENCE "public"."VaiTro_VaiTroID_seq" OWNED BY "public"."VaiTro"."VaiTroID";
CREATE VIEW "public"."banggia" AS
 SELECT "BangGiaID" AS banggiaid,
    "DichVuID" AS dichvuid,
    "LoaiDoGiatID" AS loaidogiatid,
    "DonViTinhID" AS donvitinhid,
    "DonGia" AS dongia,
    "NgayApDung" AS ngayapdung,
    "NgayKetThuc" AS ngayketthuc,
    "TrangThai" AS trangthai
   FROM "BangGia";;

CREATE VIEW "public"."danhgia" AS
 SELECT "DanhGiaID" AS danhgiaid,
    "DonHangID" AS donhangid,
    "KhachHangID" AS khachhangid,
    "SoSao" AS sosao,
    "BinhLuan" AS binhluan,
    "NgayDanhGia" AS ngaydanhgia,
    "TrangThai" AS trangthai
   FROM "DanhGia";;

CREATE VIEW "public"."dichvu" AS
 SELECT "DichVuID" AS dichvuid,
    "LoaiDichVuID" AS loaidichvuid,
    "TenDichVu" AS tendichvu,
    "MoTa" AS mota,
    "ThoiGianDuKien" AS thoigiandukien,
    "TrangThai" AS trangthai,
    "NgayTao" AS ngaytao
   FROM "DichVu";;

CREATE VIEW "public"."diemtichluy" AS
 SELECT "DiemTichLuyID" AS diemtichluyid,
    "KhachHangID" AS khachhangid,
    "DiemHienTai" AS diemhientai,
    "NgayCapNhat" AS ngaycapnhat
   FROM "DiemTichLuy";;

CREATE VIEW "public"."donvitinh" AS
 SELECT "DonViTinhID" AS donvitinhid,
    "TenDonViTinh" AS tendonvitinh,
    "KyHieu" AS kyhieu,
    "TrangThai" AS trangthai
   FROM "DonViTinh";;

CREATE VIEW "public"."hoadon" AS
 SELECT "HoaDonID" AS hoadonid,
    "MaHoaDon" AS mahoadon,
    "DonHangID" AS donhangid,
    "TongTien" AS tongtien,
    "GiamGia" AS giamgia,
    "PhiGiaoHang" AS phigiaohang,
    "ThanhTien" AS thanhtien,
    "NgayLap" AS ngaylap,
    "TrangThai" AS trangthai
   FROM "HoaDon";;

CREATE VIEW "public"."khachhang" AS
 SELECT "KhachHangID" AS khachhangid,
    "HoTen" AS hoten,
    "SoDienThoai" AS sodienthoai,
    "Email" AS email,
    "DiaChi" AS diachi,
    "NgayTao" AS ngaytao,
    "TrangThai" AS trangthai
   FROM "KhachHang";;

CREATE VIEW "public"."lichsuthaydoihoadon" AS
 SELECT "LichSuID" AS lichsuid,
    "HoaDonID" AS hoadonid,
    "TaiKhoanID" AS taikhoanid,
    "ThoiGian" AS thoigian,
    "TruongThayDoi" AS truongthaydoi,
    "GiaTriCu" AS giatricu,
    "GiaTriMoi" AS giatrimoi,
    "LyDo" AS lydo
   FROM "LichSuThayDoiHoaDon";;

CREATE VIEW "public"."loaidichvu" AS
 SELECT "LoaiDichVuID" AS loaidichvuid,
    "TenLoaiDichVu" AS tenloaidichvu,
    "MoTa" AS mota,
    "TrangThai" AS trangthai
   FROM "LoaiDichVu";;

CREATE VIEW "public"."loaidogiat" AS
 SELECT "LoaiDoGiatID" AS loaidogiatid,
    "TenLoaiDoGiat" AS tenloaidogiat,
    "MoTa" AS mota,
    "TrangThai" AS trangthai
   FROM "LoaiDoGiat";;

CREATE VIEW "public"."nhanvien" AS
 SELECT "NhanVienID" AS nhanvienid,
    "HoTen" AS hoten,
    "SoDienThoai" AS sodienthoai,
    "Email" AS email,
    "DiaChi" AS diachi,
    "ChucDanh" AS chucdanh,
    "NgayVaoLam" AS ngayvaolam,
    "TrangThai" AS trangthai
   FROM "NhanVien";;

CREATE VIEW "public"."quyen" AS
 SELECT "QuyenID" AS quyenid,
    "MaQuyen" AS maquyen,
    "TenQuyen" AS tenquyen,
    "MoTa" AS mota,
    "TrangThai" AS trangthai
   FROM "Quyen";;

CREATE VIEW "public"."taikhoan" AS
 SELECT "TaiKhoanID" AS taikhoanid,
    "TenDangNhap" AS tendangnhap,
    "MatKhau" AS matkhau,
    "Email" AS email,
    "SoDienThoai" AS sodienthoai,
    "NhanVienID" AS nhanvienid,
    "KhachHangID" AS khachhangid,
    "TrangThai" AS trangthai,
    "NgayTao" AS ngaytao,
    "UserAuthId" AS userauthid
   FROM "TaiKhoan";;

CREATE VIEW "public"."taikhoan_vaitro" AS
 SELECT "TaiKhoanID" AS taikhoanid,
    "VaiTroID" AS vaitroid
   FROM "TaiKhoan_VaiTro";;

CREATE VIEW "public"."thanhtoan" AS
 SELECT "ThanhToanID" AS thanhtoanid,
    "DonHangID" AS donhangid,
    "SoTien" AS sotien,
    "PhuongThuc" AS phuongthuc,
    "MaGiaoDich" AS magiaodich,
    "ThoiGian" AS thoigian,
    "TrangThai" AS trangthai,
    "GhiChu" AS ghichu
   FROM "ThanhToan";;

CREATE VIEW "public"."thongbao" AS
 SELECT "ThongBaoID" AS thongbaoid,
    "TaiKhoanID" AS taikhoanid,
    "DonHangID" AS donhangid,
    "LoaiThongBao" AS loaithongbao,
    "TieuDe" AS tieude,
    "NoiDung" AS noidung,
    "ThoiGianGui" AS thoigiangui,
    "DaDoc" AS dadoc
   FROM "ThongBao";;

CREATE VIEW "public"."tinnhan" AS
 SELECT "TinNhanID" AS tinnhanid,
    "NguoiGuiID" AS nguoiguiid,
    "NguoiNhanID" AS nguoinhanid,
    "DonHangID" AS donhangid,
    "NoiDung" AS noidung,
    "ThoiGianGui" AS thoigiangui,
    "TrangThai" AS trangthai
   FROM "TinNhan";;

CREATE VIEW "public"."vaitro" AS
 SELECT "VaiTroID" AS vaitroid,
    "TenVaiTro" AS tenvaitro,
    "MoTa" AS mota,
    "TrangThai" AS trangthai
   FROM "VaiTro";;

CREATE VIEW "public"."vaitro_quyen" AS
 SELECT "VaiTroID" AS vaitroid,
    "QuyenID" AS quyenid
   FROM "VaiTro_Quyen";;

CREATE INDEX "IX_Booking_KhachHangID" ON public."Booking" USING btree ("KhachHangID");
CREATE UNIQUE INDEX booking_idempotency_key_unique_idx ON public."Booking" USING btree ("IdempotencyKey") WHERE ("IdempotencyKey" IS NOT NULL);
CREATE INDEX "IX_ChiTietDonHang_DonHangID" ON public."ChiTietDonHang" USING btree ("DonHangID");
CREATE UNIQUE INDEX "UX_DonHang_BookingID" ON public."DonHang" USING btree ("BookingID") WHERE ("BookingID" IS NOT NULL);
CREATE INDEX "IX_DonHang_KhachHangID" ON public."DonHang" USING btree ("KhachHangID");
CREATE INDEX "IX_DonHang_NhanVienID" ON public."DonHang" USING btree ("NhanVienID");
CREATE INDEX "IX_DonHang_TrangThai" ON public."DonHang" USING btree ("TrangThai");
CREATE UNIQUE INDEX "DonHang_IdempotencyKey_unique_idx" ON public."DonHang" USING btree ("IdempotencyKey") WHERE ("IdempotencyKey" IS NOT NULL);
CREATE UNIQUE INDEX donhang_bookingid_unique_idx ON public."DonHang" USING btree ("BookingID") WHERE ("BookingID" IS NOT NULL);
CREATE INDEX "IX_GiaoNhan_DonHangID" ON public."GiaoNhan" USING btree ("DonHangID");
CREATE UNIQUE INDEX "TaiKhoan_UserAuthId_unique_idx" ON public."TaiKhoan" USING btree ("UserAuthId") WHERE ("UserAuthId" IS NOT NULL);
CREATE INDEX "IX_ThanhToan_DonHangID" ON public."ThanhToan" USING btree ("DonHangID");
CREATE INDEX khachhang_diachi_khachhangid_idx ON public.khachhang_diachi USING btree (khachhangid);
CREATE UNIQUE INDEX khachhang_diachi_one_default_idx ON public.khachhang_diachi USING btree (khachhangid) WHERE macdinh;
CREATE INDEX sessions_user_id_index ON public.sessions USING btree (user_id);
CREATE INDEX sessions_last_activity_index ON public.sessions USING btree (last_activity);
CREATE INDEX idx_ChiTietBooking_BookingID ON public."ChiTietBooking" USING btree ("BookingID");
CREATE INDEX idx_ChiTietBooking_DichVuID ON public."ChiTietBooking" USING btree ("DichVuID");
CREATE INDEX idx_ChiTietBooking_LoaiDoGiatID ON public."ChiTietBooking" USING btree ("LoaiDoGiatID");
CREATE INDEX idx_NhatKyHeThong_BangDuLieu_BanGhiID ON public."NhatKyHeThong" USING btree ("BangDuLieu", "BanGhiID");
CREATE INDEX idx_NhatKyHeThong_TaiKhoanID ON public."NhatKyHeThong" USING btree ("TaiKhoanID");
CREATE INDEX idx_NhatKyHeThong_ThoiGian ON public."NhatKyHeThong" USING btree ("ThoiGian");
CREATE UNIQUE INDEX ux_DonHang_BookingID_not_null ON public."DonHang" USING btree ("BookingID") WHERE ("BookingID" IS NOT NULL);
