-- TEST ONLY: disposable local database; never run this file on Supabase.
DO $$ BEGIN IF current_database()<>'laundry_rpc_test' THEN RAISE EXCEPTION 'Only the disposable laundry_rpc_test database is allowed'; END IF; END $$;
CREATE SCHEMA auth;
CREATE SCHEMA private;
CREATE SCHEMA extensions;
CREATE EXTENSION pgcrypto WITH SCHEMA extensions;
CREATE FUNCTION auth.uid() RETURNS uuid LANGUAGE sql STABLE AS $$ SELECT nullif(current_setting('test.user_id',true),'')::uuid $$;
CREATE TABLE public."BangGia" (
 "BangGiaID" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
 "DichVuID" integer NOT NULL,
 "LoaiDoGiatID" integer NOT NULL,
 "DonViTinhID" integer NOT NULL,
 "DonGia" numeric(18,2) NOT NULL,
 "NgayApDung" date NOT NULL,
 "NgayKetThuc" date,
 "TrangThai" character varying(30) DEFAULT 'Hoạt động'::character varying NOT NULL
);
CREATE TABLE public."Booking" (
 "BookingID" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
 "MaBooking" character varying(30) NOT NULL,
 "KhachHangID" integer NOT NULL,
 "HinhThucNhanDo" character varying(30) NOT NULL,
 "DiaChiNhan" text,
 "NgayHen" date NOT NULL,
 "GioHen" time without time zone NOT NULL,
 "GhiChu" character varying(500),
 "TrangThai" character varying(30) DEFAULT 'ChoTiepNhan'::character varying NOT NULL,
 "NgayTao" timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
 "NgayCapNhat" timestamp without time zone,
 "IdempotencyKey" uuid,
 "NhanVienID" integer,
 "NhanVienXacNhanID" integer,
 "ThoiGianXacNhan" timestamp without time zone,
 "DiemSuDung" integer DEFAULT 0 NOT NULL,
 "TienGiamDoDiem" numeric(18,2) DEFAULT 0 NOT NULL,
 "DiemDaTru" boolean DEFAULT false NOT NULL,
 "KhuyenMaiID" integer,
 "KhuyenMaiDaTru" boolean DEFAULT false NOT NULL,
 "PhuongThucThanhToan" character varying(30) DEFAULT 'Tiền mặt'::character varying NOT NULL,
 "HinhThucTraDo" text,
 "DiaChiTra" text,
 "HinhThucGiaoDo" character varying(30) DEFAULT 'Tại cửa hàng'::character varying NOT NULL,
 "DiaChiGiao" text,
 "PickupDistanceMeters" integer DEFAULT 0 NOT NULL,
 "PickupDeliveryFee" numeric(12,2) DEFAULT 0 NOT NULL,
 "DeliveryDistanceMeters" integer DEFAULT 0 NOT NULL,
 "DeliveryFee" numeric(12,2) DEFAULT 0 NOT NULL
);
CREATE TABLE public."ChiTietBooking" (
 "ChiTietBookingID" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
 "BookingID" integer NOT NULL,
 "DichVuID" integer NOT NULL,
 "LoaiDoGiatID" integer NOT NULL,
 "DonViTinhID" integer NOT NULL,
 "SoLuong" numeric,
 "KhoiLuong" numeric,
 "DonGia" numeric DEFAULT 0 NOT NULL,
 "ThanhTien" numeric DEFAULT 0 NOT NULL,
 "GhiChu" character varying
);
CREATE TABLE public."ChiTietDonHang" (
 "ChiTietDonHangID" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
 "DonHangID" integer NOT NULL,
 "DichVuID" integer NOT NULL,
 "LoaiDoGiatID" integer NOT NULL,
 "DonViTinhID" integer NOT NULL,
 "SoLuong" numeric(10,2),
 "KhoiLuong" numeric(10,2),
 "DonGia" numeric(18,2) NOT NULL,
 "ThanhTien" numeric(18,2) NOT NULL,
 "GhiChu" character varying(500),
 "TinhTrangTruocKhiGiat" text
);
CREATE TABLE public."DanhGia" (
 "DanhGiaID" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
 "DonHangID" integer NOT NULL,
 "KhachHangID" integer NOT NULL,
 "SoSao" integer NOT NULL,
 "BinhLuan" character varying(1000),
 "NgayDanhGia" timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
 "TrangThai" character varying(30) DEFAULT 'Hiển thị'::character varying NOT NULL
);
CREATE TABLE public."DanhMucLoaiDoGiat" (
 "DanhMucID" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
 "TenDanhMuc" character varying(100) NOT NULL,
 "MoTa" text,
 "TrangThai" character varying(30) DEFAULT 'Hoạt động'::character varying NOT NULL,
 "NgayTao" timestamp with time zone DEFAULT now() NOT NULL
);
CREATE TABLE public."DichVu" (
 "DichVuID" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
 "LoaiDichVuID" integer NOT NULL,
 "TenDichVu" character varying(150) NOT NULL,
 "MoTa" character varying(500),
 "ThoiGianDuKien" integer,
 "TrangThai" character varying(30) DEFAULT 'Hoạt động'::character varying NOT NULL,
 "NgayTao" timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);
CREATE TABLE public."DiemTichLuy" (
 "DiemTichLuyID" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
 "KhachHangID" integer NOT NULL,
 "DiemHienTai" integer DEFAULT 0 NOT NULL,
 "NgayCapNhat" timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);
CREATE TABLE public."DonHang" (
 "DonHangID" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
 "MaDonHang" character varying(30) NOT NULL,
 "BookingID" integer,
 "KhachHangID" integer NOT NULL,
 "NhanVienID" integer,
 "TrangThai" character varying(30) DEFAULT 'Chờ tiếp nhận'::character varying NOT NULL,
 "TongTien" numeric(18,2) DEFAULT 0 NOT NULL,
 "DiemSuDung" integer DEFAULT 0 NOT NULL,
 "TienGiamDoDiem" numeric(18,2) DEFAULT 0 NOT NULL,
 "KhuyenMaiID" integer,
 "TienGiamKhuyenMai" numeric(18,2) DEFAULT 0 NOT NULL,
 "PhiGiaoHang" numeric(18,2) DEFAULT 0 NOT NULL,
 "ThanhTien" numeric(18,2) DEFAULT 0 NOT NULL,
 "GhiChu" character varying(500),
 "NgayTao" timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
 "NgayCapNhat" timestamp without time zone,
 "IdempotencyKey" uuid
);
CREATE TABLE public."DonViTinh" (
 "DonViTinhID" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
 "TenDonViTinh" character varying(50) NOT NULL,
 "KyHieu" character varying(20),
 "TrangThai" character varying(30) DEFAULT 'Hoạt động'::character varying NOT NULL
);
CREATE TABLE public."GiaoNhan" (
 "GiaoNhanID" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
 "DonHangID" integer NOT NULL,
 "NhanVienID" integer,
 "LoaiGiaoNhan" character varying(30) NOT NULL,
 "HinhThuc" character varying(30) NOT NULL,
 "DiaChi" character varying(255),
 "ThoiGianDuKien" timestamp without time zone,
 "ThoiGianThucTe" timestamp without time zone,
 "PhiGiaoNhan" numeric(18,2) DEFAULT 0 NOT NULL,
 "TrangThai" character varying(30) DEFAULT 'Chờ thực hiện'::character varying NOT NULL,
 "GhiChu" character varying(500)
);
CREATE TABLE public."HoaDon" (
 "HoaDonID" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
 "MaHoaDon" character varying(30) NOT NULL,
 "DonHangID" integer NOT NULL,
 "TongTien" numeric(18,2) NOT NULL,
 "GiamGia" numeric(18,2) DEFAULT 0 NOT NULL,
 "PhiGiaoHang" numeric(18,2) DEFAULT 0 NOT NULL,
 "ThanhTien" numeric(18,2) NOT NULL,
 "NgayLap" timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
 "TrangThai" character varying(30) DEFAULT 'Chưa thanh toán'::character varying NOT NULL
);
CREATE TABLE public."KhachHang" (
 "KhachHangID" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
 "HoTen" character varying(100) NOT NULL,
 "SoDienThoai" character varying(15),
 "Email" character varying(150),
 "DiaChi" character varying(255),
 "NgayTao" timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
 "TrangThai" character varying(30) DEFAULT 'Hoạt động'::character varying NOT NULL,
 "AvatarUrl" text
);
CREATE TABLE public."KhuyenMai" (
 "KhuyenMaiID" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
 "MaKhuyenMai" character varying(50) NOT NULL,
 "TenKhuyenMai" character varying(150) NOT NULL,
 "LoaiKhuyenMai" character varying(30) NOT NULL,
 "GiaTriGiam" numeric(18,2) NOT NULL,
 "GiaTriDonToiThieu" numeric(18,2),
 "MucGiamToiDa" numeric(18,2),
 "SoLuongSuDung" integer,
 "DieuKienApDung" character varying(500),
 "NgayBatDau" date NOT NULL,
 "NgayKetThuc" date NOT NULL,
 "TrangThai" character varying(30) DEFAULT 'Hoạt động'::character varying NOT NULL
);
CREATE TABLE public."LichSuThayDoiHoaDon" (
 "LichSuID" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
 "HoaDonID" integer NOT NULL,
 "TaiKhoanID" integer NOT NULL,
 "ThoiGian" timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
 "TruongThayDoi" character varying(100) NOT NULL,
 "GiaTriCu" character varying(500),
 "GiaTriMoi" character varying(500),
 "LyDo" character varying(500)
);
CREATE TABLE public."LoaiDichVu" (
 "LoaiDichVuID" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
 "TenLoaiDichVu" character varying(100) NOT NULL,
 "MoTa" character varying(255),
 "TrangThai" character varying(30) DEFAULT 'Hoạt động'::character varying NOT NULL
);
CREATE TABLE public."LoaiDoGiat" (
 "LoaiDoGiatID" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
 "TenLoaiDoGiat" character varying(150) NOT NULL,
 "MoTa" character varying(255),
 "TrangThai" character varying(30) DEFAULT 'Hoạt động'::character varying NOT NULL,
 "DanhMucID" bigint NOT NULL
);
CREATE TABLE public."NhanVien" (
 "NhanVienID" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
 "HoTen" character varying(100) NOT NULL,
 "SoDienThoai" character varying(15) NOT NULL,
 "Email" character varying(150),
 "DiaChi" character varying(255),
 "ChucDanh" character varying(100),
 "NgayVaoLam" date,
 "TrangThai" character varying(30) DEFAULT 'Hoạt động'::character varying NOT NULL
);
CREATE TABLE public."NhatKyHeThong" (
 "NhatKyID" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
 "TaiKhoanID" integer,
 "HanhDong" character varying NOT NULL,
 "BangDuLieu" character varying NOT NULL,
 "BanGhiID" bigint,
 "DuLieuCu" jsonb,
 "DuLieuMoi" jsonb,
 "LyDo" character varying,
 "ThoiGian" timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
 "IPAddress" character varying,
 "UserAgent" character varying
);
CREATE TABLE public."Quyen" (
 "QuyenID" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
 "MaQuyen" character varying(100) NOT NULL,
 "TenQuyen" character varying(150) NOT NULL,
 "MoTa" character varying(255),
 "TrangThai" character varying(30) DEFAULT 'Hoạt động'::character varying NOT NULL
);
CREATE TABLE public."TaiKhoan" (
 "TaiKhoanID" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
 "TenDangNhap" character varying(100) NOT NULL,
 "MatKhau" character varying(255),
 "Email" character varying(150),
 "SoDienThoai" character varying(15),
 "NhanVienID" integer,
 "KhachHangID" integer,
 "TrangThai" character varying(30) DEFAULT 'Hoạt động'::character varying NOT NULL,
 "NgayTao" timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
 "UserAuthId" uuid,
 "AvatarURL" text
);
CREATE TABLE public."TaiKhoan_VaiTro" (
 "TaiKhoanID" integer NOT NULL,
 "VaiTroID" integer NOT NULL
);
CREATE TABLE public."ThanhToan" (
 "ThanhToanID" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
 "DonHangID" integer NOT NULL,
 "SoTien" numeric(18,2) NOT NULL,
 "PhuongThuc" character varying(30) NOT NULL,
 "MaGiaoDich" character varying(100),
 "ThoiGian" timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
 "TrangThai" character varying(30) DEFAULT 'Chờ thanh toán'::character varying NOT NULL,
 "GhiChu" character varying(500)
);
CREATE TABLE public."ThongBao" (
 "ThongBaoID" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
 "TaiKhoanID" integer NOT NULL,
 "DonHangID" integer,
 "LoaiThongBao" character varying(50),
 "TieuDe" character varying(200) NOT NULL,
 "NoiDung" character varying(1000) NOT NULL,
 "ThoiGianGui" timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
 "DaDoc" boolean DEFAULT false NOT NULL
);
CREATE TABLE public."TinNhan" (
 "TinNhanID" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
 "NguoiGuiID" integer NOT NULL,
 "NguoiNhanID" integer NOT NULL,
 "DonHangID" integer,
 "NoiDung" character varying(1000) NOT NULL,
 "ThoiGianGui" timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
 "TrangThai" character varying(30) DEFAULT 'Đã gửi'::character varying NOT NULL
);
CREATE TABLE public."VaiTro" (
 "VaiTroID" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
 "TenVaiTro" character varying(100) NOT NULL,
 "MoTa" character varying(255),
 "TrangThai" character varying(30) DEFAULT 'Hoạt động'::character varying NOT NULL
);
CREATE TABLE public."VaiTro_Quyen" (
 "VaiTroID" integer NOT NULL,
 "QuyenID" integer NOT NULL
);
CREATE TABLE public."delivery_fee_quotes" (
 "id" uuid DEFAULT gen_random_uuid() NOT NULL,
 "auth_user_id" uuid NOT NULL,
 "pickup_address_hash" text,
 "delivery_address_hash" text,
 "pickup_distance_meters" integer DEFAULT 0 NOT NULL,
 "delivery_distance_meters" integer DEFAULT 0 NOT NULL,
 "expires_at" timestamp with time zone NOT NULL,
 "consumed_booking_id" integer,
 "created_at" timestamp with time zone DEFAULT now() NOT NULL
);
ALTER TABLE public."DiemTichLuy" ADD UNIQUE("KhachHangID");
ALTER TABLE public."Booking" ADD UNIQUE("IdempotencyKey");
CREATE OR REPLACE FUNCTION private.account_id_for_customer(p_khachhangid bigint)
 RETURNS bigint
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO ''
AS $function$
  SELECT account."TaiKhoanID"
  FROM public."TaiKhoan" AS account
  WHERE account."KhachHangID" = p_khachhangid
    AND account."TrangThai" = 'Hoạt động'
  ORDER BY account."TaiKhoanID"
  LIMIT 1;
$function$;
CREATE OR REPLACE FUNCTION private.current_customer_id()
 RETURNS bigint
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO ''
AS $function$
  SELECT account."KhachHangID"
  FROM public."TaiKhoan" AS account
  JOIN public."KhachHang" AS customer
    ON customer."KhachHangID" = account."KhachHangID"
  WHERE account."UserAuthId" = (SELECT auth.uid())
    AND account."TrangThai" = 'Hoạt động'
    AND customer."TrangThai" = 'Hoạt động';
$function$;
CREATE OR REPLACE FUNCTION private.current_employee_id()
 RETURNS bigint
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO ''
AS $function$
  SELECT account."NhanVienID"
  FROM public."TaiKhoan" AS account
  JOIN public."NhanVien" AS employee
    ON employee."NhanVienID" = account."NhanVienID"
  WHERE account."UserAuthId" = (SELECT auth.uid())
    AND account."TrangThai" = 'Hoạt động'
    AND employee."TrangThai" = 'Hoạt động';
$function$;
CREATE OR REPLACE FUNCTION private.has_role(role_name text)
 RETURNS boolean
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO ''
AS $function$
  SELECT EXISTS (
    SELECT 1
    FROM public."TaiKhoan" AS account
    JOIN public."TaiKhoan_VaiTro" AS account_role
      ON account_role."TaiKhoanID" = account."TaiKhoanID"
    JOIN public."VaiTro" AS app_role
      ON app_role."VaiTroID" = account_role."VaiTroID"
    WHERE account."UserAuthId" = (SELECT auth.uid())
      AND account."TrangThai" = 'Hoạt động'
      AND app_role."TenVaiTro" = role_name
      AND app_role."TrangThai" = 'Hoạt động'
  );
$function$;
CREATE OR REPLACE FUNCTION private.is_staff()
 RETURNS boolean
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO ''
AS $function$
			SELECT (SELECT private.has_role('Nhân viên'))
				OR (SELECT private.has_role('Quản lý'))
				OR (SELECT private.has_role('Chủ cửa hàng'));
		$function$;
CREATE OR REPLACE FUNCTION public.request_order_payment(p_donhangid bigint, p_phuongthuc text, p_idempotency_key uuid)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
DECLARE

    customer_id bigint :=
        (SELECT private.current_customer_id());

    order_record public."DonHang"%ROWTYPE;

    invoice public."HoaDon"%ROWTYPE;

    existing_payment public."ThanhToan"%ROWTYPE;

    amount_due numeric(18,2);

    payment_id bigint;

BEGIN

    -- =====================================================
    -- 1. Kiểm tra khách hàng
    -- =====================================================

    IF (SELECT auth.uid()) IS NULL
       OR customer_id IS NULL THEN

        RAISE EXCEPTION
            'An active customer account is required';

    END IF;


    -- =====================================================
    -- 2. Kiểm tra phương thức thanh toán
    -- =====================================================

    IF p_phuongthuc NOT IN (
        'Tiền mặt',
        'Chuyển khoản'
    ) THEN

        RAISE EXCEPTION
            'Unsupported payment method';

    END IF;


    -- =====================================================
    -- 3. Kiểm tra Idempotency
    -- =====================================================

    IF p_idempotency_key IS NULL THEN

        RAISE EXCEPTION
            'An idempotency key is required';

    END IF;


    PERFORM pg_catalog.pg_advisory_xact_lock(
        pg_catalog.hashtextextended(
            p_idempotency_key::text,
            0
        )
    );


    -- =====================================================
    -- 4. Kiểm tra Payment đã tạo trước đó
    -- =====================================================

    SELECT *
    INTO existing_payment

    FROM public."ThanhToan"

    WHERE "IdempotencyKey" =
          p_idempotency_key;


    IF FOUND THEN

        IF NOT EXISTS (

            SELECT 1

            FROM public."DonHang" AS order_row

            WHERE order_row."DonHangID" =
                  existing_payment."DonHangID"

              AND order_row."KhachHangID" =
                  customer_id

        ) THEN

            RAISE EXCEPTION
                'Idempotency key is already in use';

        END IF;


        RETURN jsonb_build_object(

            'thanhtoanid',
            existing_payment."ThanhToanID",

            'sotien',
            existing_payment."SoTien",

            'trangthai',
            existing_payment."TrangThai",

            'phuongthuc',
            existing_payment."PhuongThuc"

        );

    END IF;


    -- =====================================================
    -- 5. Lấy và khóa Order
    -- =====================================================

    SELECT *
    INTO order_record

    FROM public."DonHang"

    WHERE "DonHangID" = p_donhangid

      AND "KhachHangID" = customer_id

    FOR UPDATE;


    IF NOT FOUND THEN

        RAISE EXCEPTION
            'Order not found';

    END IF;


    -- Chỉ thanh toán sau khi giao
    IF order_record."TrangThai" NOT IN (
        'Đã giao',
        'Đã thanh toán'
    ) THEN

        RAISE EXCEPTION
            'Payment is available after the order is delivered';

    END IF;


    -- =====================================================
    -- 6. Lấy Invoice
    -- =====================================================

    SELECT *
    INTO invoice

    FROM public."HoaDon"

    WHERE "DonHangID" = p_donhangid

    FOR UPDATE;


    IF NOT FOUND
       OR invoice."TrangThai" <> 'Chưa thanh toán' THEN

        RAISE EXCEPTION
            'No unpaid invoice is available';

    END IF;


    -- =====================================================
    -- 7. Tính số tiền còn phải trả
    -- =====================================================

    SELECT
        greatest(
            invoice."ThanhTien"
            -
            coalesce(
                sum(payment."SoTien")
                FILTER (
                    WHERE payment."TrangThai" =
                          'Thành công'
                ),
                0
            ),
            0
        )

    INTO amount_due

    FROM public."ThanhToan" AS payment

    WHERE payment."DonHangID" =
          p_donhangid;


    IF amount_due <= 0 THEN

        RAISE EXCEPTION
            'The invoice has no remaining balance';

    END IF;


    -- =====================================================
    -- 8. Tạo Payment
    -- =====================================================

    INSERT INTO public."ThanhToan" (

        "DonHangID",
        "PhuongThuc",
        "SoTien",
        "TrangThai",
        "IdempotencyKey",
        "GhiChu"

    )

    VALUES (

        p_donhangid,

        p_phuongthuc,

        amount_due,

        'Chờ thanh toán',

        p_idempotency_key,

        CASE
            WHEN p_phuongthuc = 'Chuyển khoản'
            THEN
                'Khách chọn chuyển khoản; chờ cửa hàng đối soát.'

            ELSE
                'Khách chọn tiền mặt; chờ cửa hàng thu tiền.'
        END

    )

    RETURNING "ThanhToanID"
    INTO payment_id;


    -- =====================================================
    -- 9. Trả kết quả
    -- =====================================================

    RETURN jsonb_build_object(

        'thanhtoanid',
        payment_id,

        'sotien',
        amount_due,

        'trangthai',
        'Chờ thanh toán',

        'phuongthuc',
        p_phuongthuc

    );

END;
$function$;
CREATE OR REPLACE FUNCTION public.set_booking_promotion(p_bookingid bigint, p_makhuyenmai text)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
DECLARE
  customer_id bigint := (SELECT private.current_customer_id());
  booking_row public."Booking"%ROWTYPE;
  promotion public."KhuyenMai"%ROWTYPE;
BEGIN
  IF (SELECT auth.uid()) IS NULL OR customer_id IS NULL THEN
    RAISE EXCEPTION 'An active customer account is required';
  END IF;

  SELECT *
  INTO booking_row
  FROM public."Booking"
  WHERE "BookingID" = p_bookingid
    AND "KhachHangID" = customer_id
  FOR UPDATE;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Booking not found';
  END IF;

  SELECT *
  INTO promotion
  FROM public."KhuyenMai"
  WHERE upper("MaKhuyenMai") = upper(btrim(p_makhuyenmai))
  FOR UPDATE;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Promotion code does not exist';
  END IF;

  IF booking_row."KhuyenMaiID" IS NOT NULL THEN
    IF booking_row."KhuyenMaiID" = promotion."KhuyenMaiID" THEN
      RETURN;
    END IF;
    RAISE EXCEPTION 'A promotion has already been reserved for this booking';
  END IF;

  IF booking_row."TrangThai" <> 'ChoTiepNhan'
     OR EXISTS (
       SELECT 1
       FROM public."DonHang"
       WHERE "BookingID" = p_bookingid
     ) THEN
    RAISE EXCEPTION 'Only pending bookings can use a promotion';
  END IF;

  IF EXISTS (
    SELECT 1
    FROM public."Booking" AS existing_booking
    WHERE existing_booking."KhachHangID" = customer_id
      AND existing_booking."KhuyenMaiID" = promotion."KhuyenMaiID"
      AND existing_booking."TrangThai" <> 'DaHuy'
  ) THEN
    RAISE EXCEPTION 'Promotion has already been used by this customer';
  END IF;

  IF promotion."TrangThai" <> 'Hoạt động'
     OR promotion."NgayBatDau" > current_date
     OR promotion."NgayKetThuc" < current_date
     OR (
       promotion."SoLuongSuDung" IS NOT NULL
       AND promotion."SoLuongSuDung" <= 0
     ) THEN
    RAISE EXCEPTION 'Promotion code is invalid, expired, or unavailable';
  END IF;

  IF promotion."SoLuongSuDung" IS NOT NULL THEN
    UPDATE public."KhuyenMai"
    SET "SoLuongSuDung" = "SoLuongSuDung" - 1
    WHERE "KhuyenMaiID" = promotion."KhuyenMaiID"
      AND "SoLuongSuDung" > 0;

    IF NOT FOUND THEN
      RAISE EXCEPTION 'Promotion code is no longer available';
    END IF;
  END IF;

  UPDATE public."Booking"
  SET "KhuyenMaiID" = promotion."KhuyenMaiID",
      "KhuyenMaiDaTru" = promotion."SoLuongSuDung" IS NOT NULL
  WHERE "BookingID" = p_bookingid;
END;
$function$;
CREATE OR REPLACE FUNCTION public.submit_laundry_booking_request(p_items jsonb, p_hinhthucnhando text, p_diachinhan text, p_ngayhen date, p_giohen time without time zone, p_ghichu text, p_idempotency_key uuid, p_use_points boolean, p_makhuyenmai text DEFAULT NULL::text)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
DECLARE
  booking_result jsonb;
BEGIN
  IF p_items IS NULL THEN
    booking_result := public.submit_laundry_booking_without_details(
      p_hinhthucnhando,
      p_diachinhan,
      p_ngayhen,
      p_giohen,
      p_ghichu,
      p_idempotency_key
    );
  ELSIF coalesce(p_use_points, false) THEN
    booking_result := public.submit_laundry_order_cart_with_points(
      p_items,
      p_hinhthucnhando,
      p_diachinhan,
      p_ngayhen,
      p_giohen,
      p_ghichu,
      p_idempotency_key,
      true
    );
  ELSE
    booking_result := public.submit_laundry_order_cart(
      p_items,
      p_hinhthucnhando,
      p_diachinhan,
      p_ngayhen,
      p_giohen,
      p_ghichu,
      p_idempotency_key
    );
  END IF;

  IF nullif(btrim(p_makhuyenmai), '') IS NOT NULL THEN
    PERFORM public.set_booking_promotion(
      (booking_result->>'bookingid')::bigint,
      p_makhuyenmai
    );
  END IF;

  RETURN booking_result;
END;
$function$;
CREATE OR REPLACE FUNCTION public.submit_laundry_booking_request(p_items jsonb, p_hinhthucnhando text, p_diachinhan text, p_ngayhen date, p_giohen time without time zone, p_ghichu text, p_idempotency_key uuid, p_use_points boolean, p_phuongthucthanhtoan text, p_makhuyenmai text DEFAULT NULL::text)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
DECLARE
  booking_result jsonb;
  customer_id bigint := (SELECT private.current_customer_id());
BEGIN
  IF p_phuongthucthanhtoan IS NULL
     OR p_phuongthucthanhtoan NOT IN ('Tiền mặt', 'Chuyển khoản') THEN
    RAISE EXCEPTION 'Unsupported payment method';
  END IF;

  booking_result := public.submit_laundry_booking_request(
    p_items => p_items,
    p_hinhthucnhando => p_hinhthucnhando,
    p_diachinhan => p_diachinhan,
    p_ngayhen => p_ngayhen,
    p_giohen => p_giohen,
    p_ghichu => p_ghichu,
    p_idempotency_key => p_idempotency_key,
    p_use_points => p_use_points,
    p_makhuyenmai => p_makhuyenmai
  );

  UPDATE public."Booking"
  SET "PhuongThucThanhToan" = p_phuongthucthanhtoan
  WHERE "BookingID" = (booking_result->>'bookingid')::bigint
    AND "KhachHangID" = customer_id;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Booking not found for current customer';
  END IF;

  RETURN booking_result;
END;
$function$;
CREATE OR REPLACE FUNCTION public.submit_laundry_booking_with_delivery(p_items jsonb, p_hinhthucnhando text, p_hinhthucgiaodo text, p_diachinhan text, p_ngayhen date, p_giohen time without time zone, p_ghichu text, p_idempotency_key uuid, p_use_points boolean, p_phuongthucthanhtoan text, p_makhuyenmai text DEFAULT NULL::text, p_diachigiao text DEFAULT NULL::text, p_delivery_fee_quote_id uuid DEFAULT NULL::uuid)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
DECLARE
  booking_result jsonb;
  customer_id bigint := (SELECT private.current_customer_id());
  current_user_id uuid := (SELECT auth.uid());
  booking_id bigint;
  quote_row public.delivery_fee_quotes%ROWTYPE;
  pickup_distance integer := 0;
  delivery_distance integer := 0;
  pickup_fee numeric(12, 2) := 0;
  delivery_fee numeric(12, 2) := 0;
  total_delivery_fee numeric(12, 2) := 0;
  pickup_address text;
  delivery_address text;
BEGIN
  IF current_user_id IS NULL OR customer_id IS NULL THEN
    RAISE EXCEPTION 'An active customer account is required';
  END IF;
  IF p_hinhthucnhando NOT IN ('Tại cửa hàng', 'Tại nhà')
     OR p_hinhthucgiaodo NOT IN ('Tại cửa hàng', 'Tại nhà') THEN
    RAISE EXCEPTION 'Unsupported delivery method';
  END IF;
  IF p_hinhthucnhando = 'Tại nhà'
     AND nullif(btrim(COALESCE(p_diachinhan, '')), '') IS NULL THEN
    RAISE EXCEPTION 'Pickup address is required';
  END IF;
  IF p_hinhthucgiaodo = 'Tại nhà'
     AND nullif(btrim(COALESCE(p_diachigiao, '')), '') IS NULL THEN
    RAISE EXCEPTION 'Delivery address is required';
  END IF;

  pickup_address := CASE WHEN p_hinhthucnhando = 'Tại nhà'
    THEN nullif(btrim(p_diachinhan), '') ELSE NULL END;
  delivery_address := CASE WHEN p_hinhthucgiaodo = 'Tại nhà'
    THEN nullif(btrim(p_diachigiao), '') ELSE NULL END;

  IF pickup_address IS NOT NULL OR delivery_address IS NOT NULL THEN
    IF p_delivery_fee_quote_id IS NULL THEN
      RAISE EXCEPTION 'A current delivery fee quote is required';
    END IF;

    SELECT * INTO quote_row
    FROM public.delivery_fee_quotes
    WHERE id = p_delivery_fee_quote_id
    FOR UPDATE;

    IF NOT FOUND
       OR quote_row.auth_user_id <> current_user_id
       OR (
         pickup_address IS NULL
         AND quote_row.pickup_address_hash IS NOT NULL
       )
       OR (
         pickup_address IS NOT NULL
         AND quote_row.pickup_address_hash IS DISTINCT FROM
           encode(extensions.digest(convert_to(btrim(pickup_address), 'UTF8'), 'sha256'), 'hex')
       )
       OR (
         delivery_address IS NULL
         AND quote_row.delivery_address_hash IS NOT NULL
       )
       OR (
         delivery_address IS NOT NULL
         AND quote_row.delivery_address_hash IS DISTINCT FROM
           encode(extensions.digest(convert_to(btrim(delivery_address), 'UTF8'), 'sha256'), 'hex')
       )
       OR (
         quote_row.expires_at <= now()
         AND quote_row.consumed_booking_id IS NULL
       ) THEN
      RAISE EXCEPTION 'Delivery fee quote is invalid or expired';
    END IF;

    IF quote_row.consumed_booking_id IS NOT NULL AND NOT EXISTS (
      SELECT 1 FROM public."Booking"
      WHERE "BookingID" = quote_row.consumed_booking_id
        AND "KhachHangID" = customer_id
        AND "IdempotencyKey" = p_idempotency_key
    ) THEN
      RAISE EXCEPTION 'Delivery fee quote has already been used';
    END IF;

    pickup_distance := CASE WHEN pickup_address IS NOT NULL
      THEN quote_row.pickup_distance_meters ELSE 0 END;
    delivery_distance := CASE WHEN delivery_address IS NOT NULL
      THEN quote_row.delivery_distance_meters ELSE 0 END;

    -- First 3,000 meters are free on each leg. Each additional meter costs
    -- 5 VND; round the fee up to the next 1,000 VND.
    pickup_fee := ceil(greatest(pickup_distance - 3000, 0)::numeric * 5 / 1000) * 1000;
    delivery_fee := ceil(greatest(delivery_distance - 3000, 0)::numeric * 5 / 1000) * 1000;
  ELSIF p_delivery_fee_quote_id IS NOT NULL THEN
    RAISE EXCEPTION 'A delivery fee quote was supplied without a home delivery leg';
  END IF;

  booking_result := public.submit_laundry_booking_request(
    p_items => p_items,
    p_hinhthucnhando => p_hinhthucnhando,
    p_diachinhan => p_diachinhan,
    p_ngayhen => p_ngayhen,
    p_giohen => p_giohen,
    p_ghichu => p_ghichu,
    p_idempotency_key => p_idempotency_key,
    p_use_points => p_use_points,
    p_phuongthucthanhtoan => p_phuongthucthanhtoan,
    p_makhuyenmai => p_makhuyenmai
  );

  booking_id := (booking_result->>'bookingid')::bigint;
  IF p_delivery_fee_quote_id IS NOT NULL
     AND quote_row.consumed_booking_id IS NOT NULL
     AND quote_row.consumed_booking_id <> booking_id THEN
    RAISE EXCEPTION 'Delivery fee quote has already been used';
  END IF;
  total_delivery_fee := pickup_fee + delivery_fee;

  UPDATE public."Booking"
  SET "HinhThucGiaoDo" = p_hinhthucgiaodo,
      "DiaChiGiao" = delivery_address,
      "PickupDistanceMeters" = pickup_distance,
      "PickupDeliveryFee" = pickup_fee,
      "DeliveryDistanceMeters" = delivery_distance,
      "DeliveryFee" = delivery_fee
  WHERE "BookingID" = booking_id
    AND "KhachHangID" = customer_id;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Booking not found for current customer';
  END IF;

  IF p_delivery_fee_quote_id IS NOT NULL THEN
    UPDATE public.delivery_fee_quotes
    SET consumed_booking_id = booking_id
    WHERE id = p_delivery_fee_quote_id;
  END IF;

  IF EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'Booking'
      AND column_name = 'HinhThucTraDo'
  ) THEN
    EXECUTE 'UPDATE public."Booking" SET "HinhThucTraDo" = $1 WHERE "BookingID" = $2'
      USING p_hinhthucgiaodo, booking_id;
  END IF;
  IF EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'Booking'
      AND column_name = 'DiaChiTra'
  ) THEN
    EXECUTE 'UPDATE public."Booking" SET "DiaChiTra" = $1 WHERE "BookingID" = $2'
      USING delivery_address, booking_id;
  END IF;

  RETURN booking_result || jsonb_build_object(
    'pickupdistancemeters', pickup_distance,
    'pickupdeliveryfee', pickup_fee,
    'deliverydistancemeters', delivery_distance,
    'deliveryfee', delivery_fee,
    'totaldeliveryfee', total_delivery_fee
  );
END;
$function$;
\i /source/docs/supabase/rpc-business-rules.rollback.sql
\i /source/docs/supabase/rpc-business-rules.sql
CREATE TRIGGER test_create_invoice AFTER INSERT ON public."DonHang" FOR EACH ROW EXECUTE FUNCTION private.create_legacy_order_invoice();
CREATE TRIGGER test_status_insert AFTER INSERT ON public."DonHang" FOR EACH ROW EXECUTE FUNCTION private.record_legacy_order_status_change();
CREATE TRIGGER test_status_update AFTER UPDATE OF "TrangThai" ON public."DonHang" FOR EACH ROW EXECUTE FUNCTION private.record_legacy_order_status_change();
CREATE TRIGGER test_booking_promo BEFORE INSERT OR UPDATE ON public."DonHang" FOR EACH ROW EXECUTE FUNCTION private.apply_booking_promotion_to_order();
