@extends('layouts.app')
@section('title', 'Chi tiết đánh giá - Sky Laundry')
@section('page-title', 'Chi tiết đánh giá')
@section('content')
<div class="d-flex justify-content-between align-items-center mb-4"><a href="{{ route('reviews.index') }}" class="btn btn-outline-secondary btn-sm"><i class="bi bi-arrow-left me-1"></i>Quay lại</a>@if(auth()->user()->isManager())<form action="{{ route('reviews.toggle', $review) }}" method="POST">@csrf @method('PATCH')<button type="submit" class="btn {{ ($review->status ?? 'visible') === 'hidden' ? 'btn-primary' : 'btn-outline-secondary' }} btn-sm"><i class="bi bi-eye{{ ($review->status ?? 'visible') === 'hidden' ? '' : '-slash' }} me-1"></i>{{ ($review->status ?? 'visible') === 'hidden' ? 'Hiện đánh giá' : 'Ẩn đánh giá' }}</button></form>@endif</div>
<div class="row g-4"><div class="col-lg-7"><div class="card h-100"><div class="card-header"><h5 class="mb-0">Nội dung đánh giá</h5></div><div class="card-body"><div class="d-flex justify-content-between align-items-center mb-3"><div class="fs-3 text-warning">@for($star = 1; $star <= 5; $star++)<i class="fas fa-star{{ $star <= $review->rating ? '' : '-regular' }}"></i>@endfor</div><span class="text-muted">{{ $review->rating }}/5 sao</span></div><p class="fs-5 mb-4">{{ $review->content ?: $review->comment ?: 'Không có nội dung' }}</p><div class="row g-3 border-top pt-3"><div class="col-md-6"><div class="small text-muted">Đơn hàng</div><a href="{{ route('orders.show', $review->order_id) }}" class="fw-semibold text-decoration-none">{{ $review->order?->code ?: '—' }}</a></div><div class="col-md-6"><div class="small text-muted">Khách hàng</div><div class="fw-semibold">{{ $review->customer?->name ?: $review->order?->customer?->name ?: '—' }}</div></div><div class="col-md-6"><div class="small text-muted">Ngày đánh giá</div><div>{{ $review->created_at?->format('d/m/Y H:i') ?: '—' }}</div></div><div class="col-md-6"><div class="small text-muted">Trạng thái</div><div>@if(($review->status ?? 'visible') === 'hidden')<span class="badge bg-secondary-subtle text-secondary">Ẩn</span>@else<span class="badge bg-success-subtle text-success">Hiển thị</span>@endif</div></div></div>
@if($review->images)<div class="border-top pt-3 mt-3"><div class="small text-muted mb-2">Hình ảnh khách hàng</div><div class="d-flex flex-wrap gap-2">@foreach((array) $review->images as $image)<img src="{{ Str::startsWith($image, 'http') ? $image : asset('storage/' . $image) }}" class="rounded" style="width: 96px; height: 96px; object-fit: cover;" alt="Ảnh đánh giá">@endforeach</div></div>@endif
</div></div></div>
<div class="col-lg-5"><div class="card" id="phan-hoi"><div class="card-header"><h5 class="mb-0">Phản hồi từ cửa hàng</h5></div><div class="card-body">@if($review->shop_response)<div class="alert alert-success"><div class="small fw-semibold mb-1">Đã phản hồi</div><div>{{ $review->shop_response }}</div><small class="d-block mt-2">{{ $review->reviewed_at?->format('d/m/Y H:i') }}</small></div>@else<p class="text-muted">Chưa có phản hồi cho đánh giá này.</p>@endif<form action="{{ route('reviews.respond', $review) }}" method="POST" class="mt-3">@csrf @method('PATCH')<label class="form-label" for="shop_response">Nội dung phản hồi <span class="text-danger ms-1">*</span></label><textarea class="form-control" id="shop_response" name="shop_response" rows="5" placeholder="Cảm ơn khách hàng đã đánh giá..." required>{{ old('shop_response', $review->shop_response) }}</textarea><button type="submit" class="btn btn-primary mt-3"><i class="bi bi-send me-1"></i>Gửi phản hồi</button></form></div></div></div></div>
@endsection