#!/usr/bin/env python3
"""Render the application's schema from reviewed, metadata-only catalog exports."""
import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
SCHEMAS = {'public', 'private'}


def ident(value):
    return '"' + value.replace('"', '""') + '"'


def qualified(schema, name):
    return ident(schema) + '.' + ident(name)


def literal(value):
    return "'" + value.replace("'", "''") + "'"


def render(catalog, grants):
    out = [
        '-- Supabase application schema snapshot; metadata only, no rows or secrets.',
        '-- Source: osnblefzulmsuthhuswl; PostgreSQL ' + catalog['server_version'],
        '-- Captured: ' + catalog['captured_at'],
        '-- Generated by scripts/schema/render.py; edit the source catalog only after a live capture.',
        '-- Includes public/private application objects and custom Storage policies.',
        '-- Requires Supabase-managed auth/storage/realtime schemas, roles and extensions.',
        '-- Fresh-project restore only. Never run this file as an upgrade on production.',
        'SET check_function_bodies = false;',
        'SET search_path = public, pg_catalog;',
        'CREATE SCHEMA IF NOT EXISTS private;',
    ]
    # A new Supabase target may have permissive per-schema defaults. Reset the
    # platform/application roles before creating objects; replay source defaults
    # only after the explicit object ACLs have been restored.
    roles = sorted({g['grantee'] for g in grants['objects']} | {'PUBLIC', 'anon', 'authenticated', 'service_role'})
    owners = sorted({r['owner'] for r in catalog['routines']}
                    | {g['owner'] for g in grants['defaults'] or []})
    role_sql = ', '.join('PUBLIC' if r == 'PUBLIC' else ident(r) for r in roles)
    for owner in owners:
        for schema in sorted(SCHEMAS):
            for kind in ['TABLES', 'SEQUENCES', 'FUNCTIONS']:
                out.append('ALTER DEFAULT PRIVILEGES FOR ROLE ' + ident(owner) + ' IN SCHEMA '
                           + ident(schema) + ' REVOKE ALL ON ' + kind + ' FROM ' + role_sql + ';')
    sequences = catalog['sequences'] or []
    for s in sequences:
        if s['dependency'] == 'i':
            continue  # Identity sequences are created with their owning columns.
        out.append(sequence_sql(s))
    tables = [t for t in catalog['tables'] if t['schema'] in SCHEMAS]
    for t in tables:
        if t['kind'] != 'r':
            continue
        columns = []
        for a in t['columns']:
            column = ident(a['name']) + ' ' + a['type']
            if a['collation']:
                column += ' COLLATE ' + a['collation']
            if a['identity']:
                s = next(s for s in sequences if s['table_schema'] == t['schema']
                         and s['table'] == t['name'] and s['column'] == a['name'])
                column += ' GENERATED ' + ('ALWAYS' if a['identity'] == 'a' else 'BY DEFAULT')
                column += ' AS IDENTITY (SEQUENCE NAME ' + qualified(s['schema'], s['name'])
                column += ' ' + sequence_options(s) + ')'
            elif a['generated']:
                column += ' GENERATED ALWAYS AS (' + a['default'] + ') STORED'
            elif a['default'] is not None:
                column += ' DEFAULT ' + a['default']
            if a['not_null']:
                column += ' NOT NULL'
            columns.append('    ' + column)
        out.append('CREATE TABLE ' + qualified(t['schema'], t['name']) + ' (\n' + ',\n'.join(columns) + '\n);')
        if t['options']:
            out.append('ALTER TABLE ' + qualified(t['schema'], t['name']) + ' SET (' + ', '.join(t['options']) + ');')
    for s in sequences:
        if s['dependency'] == 'a':
            out.append('ALTER SEQUENCE ' + qualified(s['schema'], s['name']) + ' OWNED BY '
                       + qualified(s['table_schema'], s['table']) + '.' + ident(s['column']) + ';')
    # All tables exist before any foreign key is added.
    for foreign in (False, True):
        for t in tables:
            for c in t['constraints'] or []:
                if (c['type'] == 'f') == foreign:
                    out.append('ALTER TABLE ' + qualified(t['schema'], t['name']) + ' ADD CONSTRAINT '
                               + ident(c['name']) + ' ' + c['definition'] + ';')
    for t in tables:
        if t['kind'] == 'v':
            options = ' WITH (' + ', '.join(t['options']) + ')' if t['options'] else ''
            out.append('CREATE VIEW ' + qualified(t['schema'], t['name']) + options
                       + ' AS\n' + t['view_definition'].rstrip(';') + ';')
        for i in t['indexes'] or []:
            if not i['constraint_backed']:
                out.append(i['definition'] + ';')
    for routine in catalog['routines']:
        out.append(routine['definition'].rstrip(';') + ';')
        if routine['comment']:
            out.append('COMMENT ON FUNCTION ' + qualified(routine['schema'], routine['name'])
                       + '(' + routine['identity_args'] + ') IS ' + literal(routine['comment']) + ';')
    for t in catalog['triggers']:
        if t['schema'] not in SCHEMAS and t['function_schema'] not in SCHEMAS:
            continue
        out.append(t['definition'] + ';')
        if t['enabled'] != 'O':
            action = {'D': 'DISABLE', 'R': 'ENABLE REPLICA', 'A': 'ENABLE ALWAYS'}[t['enabled']]
            out.append('ALTER TABLE ' + qualified(t['schema'], t['table']) + ' ' + action + ' TRIGGER ' + ident(t['name']) + ';')
    for t in tables:
        name = qualified(t['schema'], t['name'])
        if t['rls']:
            out.append('ALTER TABLE ' + name + ' ENABLE ROW LEVEL SECURITY;')
        if t['force_rls']:
            out.append('ALTER TABLE ' + name + ' FORCE ROW LEVEL SECURITY;')
        if t['kind'] == 'r' and t['replica_identity'] != 'd':
            mode = {'f': 'FULL', 'n': 'NOTHING'}.get(t['replica_identity'])
            if mode is None:
                raise ValueError('Index replica identity needs an explicit catalog entry')
            out.append('ALTER TABLE ' + name + ' REPLICA IDENTITY ' + mode + ';')
        if t['comment']:
            out.append('COMMENT ON ' + ('VIEW' if t['kind'] == 'v' else 'TABLE') + ' ' + name + ' IS ' + literal(t['comment']) + ';')
        for a in t['columns']:
            if a['comment']:
                out.append('COMMENT ON COLUMN ' + name + '.' + ident(a['name']) + ' IS ' + literal(a['comment']) + ';')
    for p in catalog['policies']:
        if p['schemaname'] not in SCHEMAS | {'storage'}:
            continue
        roles = ', '.join('PUBLIC' if r == 'public' else ident(r) for r in p['roles'])
        sql = 'CREATE POLICY ' + ident(p['policyname']) + ' ON ' + qualified(p['schemaname'], p['tablename'])
        sql += ' AS ' + p['permissive'] + ' FOR ' + p['cmd'] + ' TO ' + roles
        if p['qual'] is not None:
            sql += ' USING (' + p['qual'] + ')'
        if p['with_check'] is not None:
            sql += ' WITH CHECK (' + p['with_check'] + ')'
        out.append(sql + ';')
    # Clear target-inherited grants as well as implicit PUBLIC execute/USAGE.
    objects = sorted({(g['kind'], g['name']) for g in grants['objects'] if g['kind'] != 'COLUMN'})
    for kind, name in objects:
        out.append('REVOKE ALL ON ' + kind + ' ' + name + ' FROM ' + role_sql + ';')
    grouped = {}
    for g in grants['objects']:
        if g['kind'] == 'COLUMN':
            out.append('GRANT ' + g['privilege'] + ' (' + ident(g['column']) + ') ON TABLE ' + g['name']
                       + ' TO ' + ('PUBLIC' if g['grantee'] == 'PUBLIC' else ident(g['grantee']))
                       + (' WITH GRANT OPTION' if g['grantable'] else '') + ';')
            continue
        key = (g['kind'], g['name'], g['grantee'], g['grantable'])
        grouped.setdefault(key, set()).add(g['privilege'])
    for (kind, name, role, grantable), privileges in sorted(grouped.items()):
        out.append('GRANT ' + ', '.join(sorted(privileges)) + ' ON ' + kind + ' ' + name
                   + ' TO ' + ('PUBLIC' if role == 'PUBLIC' else ident(role))
                   + (' WITH GRANT OPTION' if grantable else '') + ';')
    default_types = {'r': 'TABLES', 'S': 'SEQUENCES', 'f': 'FUNCTIONS', 'T': 'TYPES', 'n': 'SCHEMAS'}
    for g in grants['defaults'] or []:
        out.append('ALTER DEFAULT PRIVILEGES FOR ROLE ' + ident(g['owner']) + ' IN SCHEMA ' + ident(g['schema'])
                   + ' GRANT ' + g['privilege'] + ' ON ' + default_types[g['type']] + ' TO '
                   + ('PUBLIC' if g['grantee'] == 'PUBLIC' else ident(g['grantee']))
                   + (' WITH GRANT OPTION' if g['grantable'] else '') + ';')
    for p in catalog['publications'] or []:
        application = [t for t in p['tables'] or [] if t['schemaname'] in SCHEMAS]
        if application and not p['all_tables']:
            out.append('ALTER PUBLICATION ' + ident(p['name']) + ' ADD TABLE '
                       + ', '.join(qualified(t['schemaname'], t['tablename']) for t in application) + ';')
    out.append('SET check_function_bodies = true;')
    return ('\n\n'.join(out) + '\n').replace('\r\n', '\n')


def sequence_options(s):
    return (f"START WITH {s['start']} INCREMENT BY {s['increment']} MINVALUE {s['min']} "
            f"MAXVALUE {s['max']} CACHE {s['cache']} " + ('CYCLE' if s['cycle'] else 'NO CYCLE'))


def sequence_sql(s):
    return 'CREATE SEQUENCE ' + qualified(s['schema'], s['name']) + ' AS ' + s['type'] + ' ' + sequence_options(s) + ';'


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    catalog = json.loads((ROOT / 'database/schema/supabase-catalog.json').read_text())
    grants = json.loads((ROOT / 'database/schema/grants.json').read_text())
    snapshot = render(catalog, grants)
    target = ROOT / 'schema.sql'
    if args.check:
        if target.read_text() != snapshot:
            raise SystemExit('schema.sql differs from the captured catalog; run scripts/schema/render.py')
        print('PASS: schema.sql matches the captured catalog')
    else:
        target.write_text(snapshot)
